// Code generated by mockery v2.53.4. DO NOT EDIT.

package providermock

import (
	mock "github.com/stretchr/testify/mock"

	service "github.com/asgardeo/thunder/internal/system/healthcheck/service"
)

// MockHealthCheckProviderInterface is an autogenerated mock type for the HealthCheckProviderInterface type
type MockHealthCheckProviderInterface struct {
	mock.Mock
}

type MockHealthCheckProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckProviderInterface) EXPECT() *MockHealthCheckProviderInterface_Expecter {
	return &MockHealthCheckProviderInterface_Expecter{mock: &_m.Mock}
}

// GetHealthCheckService provides a mock function with no fields
func (_m *MockHealthCheckProviderInterface) GetHealthCheckService() service.HealthCheckServiceInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealthCheckService")
	}

	var r0 service.HealthCheckServiceInterface
	if rf, ok := ret.Get(0).(func() service.HealthCheckServiceInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.HealthCheckServiceInterface)
		}
	}

	return r0
}

// MockHealthCheckProviderInterface_GetHealthCheckService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthCheckService'
type MockHealthCheckProviderInterface_GetHealthCheckService_Call struct {
	*mock.Call
}

// GetHealthCheckService is a helper method to define mock.On call
func (_e *MockHealthCheckProviderInterface_Expecter) GetHealthCheckService() *MockHealthCheckProviderInterface_GetHealthCheckService_Call {
	return &MockHealthCheckProviderInterface_GetHealthCheckService_Call{Call: _e.mock.On("GetHealthCheckService")}
}

func (_c *MockHealthCheckProviderInterface_GetHealthCheckService_Call) Run(run func()) *MockHealthCheckProviderInterface_GetHealthCheckService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckProviderInterface_GetHealthCheckService_Call) Return(_a0 service.HealthCheckServiceInterface) *MockHealthCheckProviderInterface_GetHealthCheckService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckProviderInterface_GetHealthCheckService_Call) RunAndReturn(run func() service.HealthCheckServiceInterface) *MockHealthCheckProviderInterface_GetHealthCheckService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckProviderInterface creates a new instance of MockHealthCheckProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckProviderInterface {
	mock := &MockHealthCheckProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
