// Code generated by mockery v2.53.5. DO NOT EDIT.

package ou

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	serviceerror "github.com/asgardeo/thunder/internal/system/error/serviceerror"
)

// OrganizationUnitServiceInterfaceMock is an autogenerated mock type for the OrganizationUnitServiceInterface type
type OrganizationUnitServiceInterfaceMock struct {
	mock.Mock
}

type OrganizationUnitServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationUnitServiceInterfaceMock) EXPECT() *OrganizationUnitServiceInterfaceMock_Expecter {
	return &OrganizationUnitServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateOrganizationUnit provides a mock function with given fields: request
func (_m *OrganizationUnitServiceInterfaceMock) CreateOrganizationUnit(request OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationUnit")
	}

	var r0 OrganizationUnit
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(OrganizationUnitRequest) OrganizationUnit); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(OrganizationUnit)
	}

	if rf, ok := ret.Get(1).(func(OrganizationUnitRequest) *serviceerror.ServiceError); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationUnit'
type OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call struct {
	*mock.Call
}

// CreateOrganizationUnit is a helper method to define mock.On call
//   - request OrganizationUnitRequest
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) CreateOrganizationUnit(request interface{}) *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call {
	return &OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call{Call: _e.mock.On("CreateOrganizationUnit", request)}
}

func (_c *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call) Run(run func(request OrganizationUnitRequest)) *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(OrganizationUnitRequest))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call) Return(_a0 OrganizationUnit, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call) RunAndReturn(run func(OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_CreateOrganizationUnit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganizationUnit provides a mock function with given fields: id
func (_m *OrganizationUnitServiceInterfaceMock) DeleteOrganizationUnit(id string) *serviceerror.ServiceError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationUnit")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganizationUnit'
type OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call struct {
	*mock.Call
}

// DeleteOrganizationUnit is a helper method to define mock.On call
//   - id string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) DeleteOrganizationUnit(id interface{}) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call {
	return &OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call{Call: _e.mock.On("DeleteOrganizationUnit", id)}
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call) Run(run func(id string)) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call) Return(_a0 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call) RunAndReturn(run func(string) *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganizationUnitByPath provides a mock function with given fields: handlePath
func (_m *OrganizationUnitServiceInterfaceMock) DeleteOrganizationUnitByPath(handlePath string) *serviceerror.ServiceError {
	ret := _m.Called(handlePath)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationUnitByPath")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = rf(handlePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganizationUnitByPath'
type OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call struct {
	*mock.Call
}

// DeleteOrganizationUnitByPath is a helper method to define mock.On call
//   - handlePath string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) DeleteOrganizationUnitByPath(handlePath interface{}) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call{Call: _e.mock.On("DeleteOrganizationUnitByPath", handlePath)}
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call) Run(run func(handlePath string)) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call) Return(_a0 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call) RunAndReturn(run func(string) *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_DeleteOrganizationUnitByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnit provides a mock function with given fields: ctx, id
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnit(ctx context.Context, id string) (OrganizationUnit, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnit")
	}

	var r0 OrganizationUnit
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string) (OrganizationUnit, *serviceerror.ServiceError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) OrganizationUnit); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(OrganizationUnit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnit'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call struct {
	*mock.Call
}

// GetOrganizationUnit is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnit(ctx interface{}, id interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call{Call: _e.mock.On("GetOrganizationUnit", ctx, id)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call) Run(run func(ctx context.Context, id string)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call) Return(_a0 OrganizationUnit, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call) RunAndReturn(run func(context.Context, string) (OrganizationUnit, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnit_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitByPath provides a mock function with given fields: ctx, handlePath
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitByPath(ctx context.Context, handlePath string) (OrganizationUnit, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, handlePath)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitByPath")
	}

	var r0 OrganizationUnit
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string) (OrganizationUnit, *serviceerror.ServiceError)); ok {
		return rf(ctx, handlePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) OrganizationUnit); ok {
		r0 = rf(ctx, handlePath)
	} else {
		r0 = ret.Get(0).(OrganizationUnit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, handlePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitByPath'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call struct {
	*mock.Call
}

// GetOrganizationUnitByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - handlePath string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitByPath(ctx interface{}, handlePath interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call{Call: _e.mock.On("GetOrganizationUnitByPath", ctx, handlePath)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call) Run(run func(ctx context.Context, handlePath string)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call) Return(_a0 OrganizationUnit, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call) RunAndReturn(run func(context.Context, string) (OrganizationUnit, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitChildren provides a mock function with given fields: ctx, id, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitChildren(ctx context.Context, id string, limit int, offset int) (*OrganizationUnitListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, id, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitChildren")
	}

	var r0 *OrganizationUnitListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, id, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *OrganizationUnitListResponse); ok {
		r0 = rf(ctx, id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrganizationUnitListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, id, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitChildren'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call struct {
	*mock.Call
}

// GetOrganizationUnitChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitChildren(ctx interface{}, id interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call{Call: _e.mock.On("GetOrganizationUnitChildren", ctx, id, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call) Run(run func(ctx context.Context, id string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call) Return(_a0 *OrganizationUnitListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call) RunAndReturn(run func(context.Context, string, int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitChildrenByPath provides a mock function with given fields: ctx, handlePath, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitChildrenByPath(ctx context.Context, handlePath string, limit int, offset int) (*OrganizationUnitListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(ctx, handlePath, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitChildrenByPath")
	}

	var r0 *OrganizationUnitListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)); ok {
		return rf(ctx, handlePath, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *OrganizationUnitListResponse); ok {
		r0 = rf(ctx, handlePath, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrganizationUnitListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(ctx, handlePath, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitChildrenByPath'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call struct {
	*mock.Call
}

// GetOrganizationUnitChildrenByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - handlePath string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitChildrenByPath(ctx interface{}, handlePath interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call{Call: _e.mock.On("GetOrganizationUnitChildrenByPath", ctx, handlePath, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call) Run(run func(ctx context.Context, handlePath string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call) Return(_a0 *OrganizationUnitListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call) RunAndReturn(run func(context.Context, string, int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitChildrenByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitGroups provides a mock function with given fields: id, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitGroups(id string, limit int, offset int) (*GroupListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(id, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitGroups")
	}

	var r0 *GroupListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, int, int) (*GroupListResponse, *serviceerror.ServiceError)); ok {
		return rf(id, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *GroupListResponse); ok {
		r0 = rf(id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GroupListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(id, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitGroups'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call struct {
	*mock.Call
}

// GetOrganizationUnitGroups is a helper method to define mock.On call
//   - id string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitGroups(id interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call{Call: _e.mock.On("GetOrganizationUnitGroups", id, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call) Run(run func(id string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call) Return(_a0 *GroupListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call) RunAndReturn(run func(string, int, int) (*GroupListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitGroupsByPath provides a mock function with given fields: handlePath, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitGroupsByPath(handlePath string, limit int, offset int) (*GroupListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(handlePath, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitGroupsByPath")
	}

	var r0 *GroupListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, int, int) (*GroupListResponse, *serviceerror.ServiceError)); ok {
		return rf(handlePath, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *GroupListResponse); ok {
		r0 = rf(handlePath, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GroupListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(handlePath, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitGroupsByPath'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call struct {
	*mock.Call
}

// GetOrganizationUnitGroupsByPath is a helper method to define mock.On call
//   - handlePath string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitGroupsByPath(handlePath interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call{Call: _e.mock.On("GetOrganizationUnitGroupsByPath", handlePath, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call) Run(run func(handlePath string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call) Return(_a0 *GroupListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call) RunAndReturn(run func(string, int, int) (*GroupListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitGroupsByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitList provides a mock function with given fields: limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitList(limit int, offset int) (*OrganizationUnitListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitList")
	}

	var r0 *OrganizationUnitListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) *OrganizationUnitListResponse); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrganizationUnitListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) *serviceerror.ServiceError); ok {
		r1 = rf(limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitList'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call struct {
	*mock.Call
}

// GetOrganizationUnitList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitList(limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call{Call: _e.mock.On("GetOrganizationUnitList", limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call) Run(run func(limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call) Return(_a0 *OrganizationUnitListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call) RunAndReturn(run func(int, int) (*OrganizationUnitListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitList_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitUsers provides a mock function with given fields: id, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitUsers(id string, limit int, offset int) (*UserListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(id, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitUsers")
	}

	var r0 *UserListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, int, int) (*UserListResponse, *serviceerror.ServiceError)); ok {
		return rf(id, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *UserListResponse); ok {
		r0 = rf(id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(id, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitUsers'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call struct {
	*mock.Call
}

// GetOrganizationUnitUsers is a helper method to define mock.On call
//   - id string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitUsers(id interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call{Call: _e.mock.On("GetOrganizationUnitUsers", id, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call) Run(run func(id string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call) Return(_a0 *UserListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call) RunAndReturn(run func(string, int, int) (*UserListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationUnitUsersByPath provides a mock function with given fields: handlePath, limit, offset
func (_m *OrganizationUnitServiceInterfaceMock) GetOrganizationUnitUsersByPath(handlePath string, limit int, offset int) (*UserListResponse, *serviceerror.ServiceError) {
	ret := _m.Called(handlePath, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationUnitUsersByPath")
	}

	var r0 *UserListResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, int, int) (*UserListResponse, *serviceerror.ServiceError)); ok {
		return rf(handlePath, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *UserListResponse); ok {
		r0 = rf(handlePath, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = rf(handlePath, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationUnitUsersByPath'
type OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call struct {
	*mock.Call
}

// GetOrganizationUnitUsersByPath is a helper method to define mock.On call
//   - handlePath string
//   - limit int
//   - offset int
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) GetOrganizationUnitUsersByPath(handlePath interface{}, limit interface{}, offset interface{}) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call{Call: _e.mock.On("GetOrganizationUnitUsersByPath", handlePath, limit, offset)}
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call) Run(run func(handlePath string, limit int, offset int)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call) Return(_a0 *UserListResponse, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call) RunAndReturn(run func(string, int, int) (*UserListResponse, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_GetOrganizationUnitUsersByPath_Call {
	_c.Call.Return(run)
	return _c
}

// IsOrganizationUnitExists provides a mock function with given fields: id
func (_m *OrganizationUnitServiceInterfaceMock) IsOrganizationUnitExists(id string) (bool, *serviceerror.ServiceError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsOrganizationUnitExists")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string) (bool, *serviceerror.ServiceError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOrganizationUnitExists'
type OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call struct {
	*mock.Call
}

// IsOrganizationUnitExists is a helper method to define mock.On call
//   - id string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) IsOrganizationUnitExists(id interface{}) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call {
	return &OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call{Call: _e.mock.On("IsOrganizationUnitExists", id)}
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call) Run(run func(id string)) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call) Return(_a0 bool, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call) RunAndReturn(run func(string) (bool, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsOrganizationUnitImmutable provides a mock function with given fields: id
func (_m *OrganizationUnitServiceInterfaceMock) IsOrganizationUnitImmutable(id string) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsOrganizationUnitImmutable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOrganizationUnitImmutable'
type OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call struct {
	*mock.Call
}

// IsOrganizationUnitImmutable is a helper method to define mock.On call
//   - id string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) IsOrganizationUnitImmutable(id interface{}) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call {
	return &OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call{Call: _e.mock.On("IsOrganizationUnitImmutable", id)}
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call) Run(run func(id string)) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call) Return(_a0 bool) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call) RunAndReturn(run func(string) bool) *OrganizationUnitServiceInterfaceMock_IsOrganizationUnitImmutable_Call {
	_c.Call.Return(run)
	return _c
}

// IsParent provides a mock function with given fields: parentID, childID
func (_m *OrganizationUnitServiceInterfaceMock) IsParent(parentID string, childID string) (bool, *serviceerror.ServiceError) {
	ret := _m.Called(parentID, childID)

	if len(ret) == 0 {
		panic("no return value specified for IsParent")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, string) (bool, *serviceerror.ServiceError)); ok {
		return rf(parentID, childID)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(parentID, childID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = rf(parentID, childID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_IsParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsParent'
type OrganizationUnitServiceInterfaceMock_IsParent_Call struct {
	*mock.Call
}

// IsParent is a helper method to define mock.On call
//   - parentID string
//   - childID string
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) IsParent(parentID interface{}, childID interface{}) *OrganizationUnitServiceInterfaceMock_IsParent_Call {
	return &OrganizationUnitServiceInterfaceMock_IsParent_Call{Call: _e.mock.On("IsParent", parentID, childID)}
}

func (_c *OrganizationUnitServiceInterfaceMock_IsParent_Call) Run(run func(parentID string, childID string)) *OrganizationUnitServiceInterfaceMock_IsParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsParent_Call) Return(_a0 bool, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_IsParent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_IsParent_Call) RunAndReturn(run func(string, string) (bool, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_IsParent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationUnit provides a mock function with given fields: id, request
func (_m *OrganizationUnitServiceInterfaceMock) UpdateOrganizationUnit(id string, request OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError) {
	ret := _m.Called(id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationUnit")
	}

	var r0 OrganizationUnit
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)); ok {
		return rf(id, request)
	}
	if rf, ok := ret.Get(0).(func(string, OrganizationUnitRequest) OrganizationUnit); ok {
		r0 = rf(id, request)
	} else {
		r0 = ret.Get(0).(OrganizationUnit)
	}

	if rf, ok := ret.Get(1).(func(string, OrganizationUnitRequest) *serviceerror.ServiceError); ok {
		r1 = rf(id, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationUnit'
type OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call struct {
	*mock.Call
}

// UpdateOrganizationUnit is a helper method to define mock.On call
//   - id string
//   - request OrganizationUnitRequest
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) UpdateOrganizationUnit(id interface{}, request interface{}) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call {
	return &OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call{Call: _e.mock.On("UpdateOrganizationUnit", id, request)}
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call) Run(run func(id string, request OrganizationUnitRequest)) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(OrganizationUnitRequest))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call) Return(_a0 OrganizationUnit, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call) RunAndReturn(run func(string, OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationUnitByPath provides a mock function with given fields: handlePath, request
func (_m *OrganizationUnitServiceInterfaceMock) UpdateOrganizationUnitByPath(handlePath string, request OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError) {
	ret := _m.Called(handlePath, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationUnitByPath")
	}

	var r0 OrganizationUnit
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)); ok {
		return rf(handlePath, request)
	}
	if rf, ok := ret.Get(0).(func(string, OrganizationUnitRequest) OrganizationUnit); ok {
		r0 = rf(handlePath, request)
	} else {
		r0 = ret.Get(0).(OrganizationUnit)
	}

	if rf, ok := ret.Get(1).(func(string, OrganizationUnitRequest) *serviceerror.ServiceError); ok {
		r1 = rf(handlePath, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationUnitByPath'
type OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call struct {
	*mock.Call
}

// UpdateOrganizationUnitByPath is a helper method to define mock.On call
//   - handlePath string
//   - request OrganizationUnitRequest
func (_e *OrganizationUnitServiceInterfaceMock_Expecter) UpdateOrganizationUnitByPath(handlePath interface{}, request interface{}) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call {
	return &OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call{Call: _e.mock.On("UpdateOrganizationUnitByPath", handlePath, request)}
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call) Run(run func(handlePath string, request OrganizationUnitRequest)) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(OrganizationUnitRequest))
	})
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call) Return(_a0 OrganizationUnit, _a1 *serviceerror.ServiceError) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call) RunAndReturn(run func(string, OrganizationUnitRequest) (OrganizationUnit, *serviceerror.ServiceError)) *OrganizationUnitServiceInterfaceMock_UpdateOrganizationUnitByPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationUnitServiceInterfaceMock creates a new instance of OrganizationUnitServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationUnitServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationUnitServiceInterfaceMock {
	mock := &OrganizationUnitServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
