// Code generated by mockery v2.53.4. DO NOT EDIT.

package jwtmock

import (
	rsa "crypto/rsa"

	mock "github.com/stretchr/testify/mock"
)

// MockJWTServiceInterface is an autogenerated mock type for the JWTServiceInterface type
type MockJWTServiceInterface struct {
	mock.Mock
}

type MockJWTServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTServiceInterface) EXPECT() *MockJWTServiceInterface_Expecter {
	return &MockJWTServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function with given fields: sub, aud, validityPeriod, claims
func (_m *MockJWTServiceInterface) GenerateJWT(sub string, aud string, validityPeriod int64, claims map[string]string) (string, int64, error) {
	ret := _m.Called(sub, aud, validityPeriod, claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int64, map[string]string) (string, int64, error)); ok {
		return rf(sub, aud, validityPeriod, claims)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, map[string]string) string); ok {
		r0 = rf(sub, aud, validityPeriod, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, map[string]string) int64); ok {
		r1 = rf(sub, aud, validityPeriod, claims)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, int64, map[string]string) error); ok {
		r2 = rf(sub, aud, validityPeriod, claims)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJWTServiceInterface_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type MockJWTServiceInterface_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - sub string
//   - aud string
//   - validityPeriod int64
//   - claims map[string]string
func (_e *MockJWTServiceInterface_Expecter) GenerateJWT(sub interface{}, aud interface{}, validityPeriod interface{}, claims interface{}) *MockJWTServiceInterface_GenerateJWT_Call {
	return &MockJWTServiceInterface_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", sub, aud, validityPeriod, claims)}
}

func (_c *MockJWTServiceInterface_GenerateJWT_Call) Run(run func(sub string, aud string, validityPeriod int64, claims map[string]string)) *MockJWTServiceInterface_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockJWTServiceInterface_GenerateJWT_Call) Return(_a0 string, _a1 int64, _a2 error) *MockJWTServiceInterface_GenerateJWT_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJWTServiceInterface_GenerateJWT_Call) RunAndReturn(run func(string, string, int64, map[string]string) (string, int64, error)) *MockJWTServiceInterface_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKey provides a mock function with no fields
func (_m *MockJWTServiceInterface) GetPublicKey() *rsa.PublicKey {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *rsa.PublicKey
	if rf, ok := ret.Get(0).(func() *rsa.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	return r0
}

// MockJWTServiceInterface_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type MockJWTServiceInterface_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
func (_e *MockJWTServiceInterface_Expecter) GetPublicKey() *MockJWTServiceInterface_GetPublicKey_Call {
	return &MockJWTServiceInterface_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey")}
}

func (_c *MockJWTServiceInterface_GetPublicKey_Call) Run(run func()) *MockJWTServiceInterface_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJWTServiceInterface_GetPublicKey_Call) Return(_a0 *rsa.PublicKey) *MockJWTServiceInterface_GetPublicKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJWTServiceInterface_GetPublicKey_Call) RunAndReturn(run func() *rsa.PublicKey) *MockJWTServiceInterface_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with no fields
func (_m *MockJWTServiceInterface) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJWTServiceInterface_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockJWTServiceInterface_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockJWTServiceInterface_Expecter) Init() *MockJWTServiceInterface_Init_Call {
	return &MockJWTServiceInterface_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockJWTServiceInterface_Init_Call) Run(run func()) *MockJWTServiceInterface_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJWTServiceInterface_Init_Call) Return(_a0 error) *MockJWTServiceInterface_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJWTServiceInterface_Init_Call) RunAndReturn(run func() error) *MockJWTServiceInterface_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTServiceInterface creates a new instance of MockJWTServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTServiceInterface {
	mock := &MockJWTServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
