// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwemock

import (
	"crypto"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/system/jose/jwe"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceInterfaceMock creates a new instance of ServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterfaceMock {
	mock := &ServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceInterfaceMock is an autogenerated mock type for the ServiceInterface type
type ServiceInterfaceMock struct {
	mock.Mock
}

type ServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterfaceMock) EXPECT() *ServiceInterfaceMock_Expecter {
	return &ServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) Decrypt(jweToken string) ([]byte, *serviceerror.ServiceError) {
	ret := _mock.Called(jweToken)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, *serviceerror.ServiceError)); ok {
		return returnFunc(jweToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(jweToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(jweToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type ServiceInterfaceMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - jweToken string
func (_e *ServiceInterfaceMock_Expecter) Decrypt(jweToken interface{}) *ServiceInterfaceMock_Decrypt_Call {
	return &ServiceInterfaceMock_Decrypt_Call{Call: _e.mock.On("Decrypt", jweToken)}
}

func (_c *ServiceInterfaceMock_Decrypt_Call) Run(run func(jweToken string)) *ServiceInterfaceMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_Decrypt_Call) Return(bytes []byte, serviceError *serviceerror.ServiceError) *ServiceInterfaceMock_Decrypt_Call {
	_c.Call.Return(bytes, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_Decrypt_Call) RunAndReturn(run func(jweToken string) ([]byte, *serviceerror.ServiceError)) *ServiceInterfaceMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type ServiceInterfaceMock
func (_mock *ServiceInterfaceMock) Encrypt(payload []byte, recipientPublicKey crypto.PublicKey, alg jwe.KeyEncAlgorithm, enc jwe.ContentEncAlgorithm) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(payload, recipientPublicKey, alg, enc)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func([]byte, crypto.PublicKey, jwe.KeyEncAlgorithm, jwe.ContentEncAlgorithm) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(payload, recipientPublicKey, alg, enc)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, crypto.PublicKey, jwe.KeyEncAlgorithm, jwe.ContentEncAlgorithm) string); ok {
		r0 = returnFunc(payload, recipientPublicKey, alg, enc)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, crypto.PublicKey, jwe.KeyEncAlgorithm, jwe.ContentEncAlgorithm) *serviceerror.ServiceError); ok {
		r1 = returnFunc(payload, recipientPublicKey, alg, enc)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ServiceInterfaceMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type ServiceInterfaceMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - payload []byte
//   - recipientPublicKey crypto.PublicKey
//   - alg jwe.KeyEncAlgorithm
//   - enc jwe.ContentEncAlgorithm
func (_e *ServiceInterfaceMock_Expecter) Encrypt(payload interface{}, recipientPublicKey interface{}, alg interface{}, enc interface{}) *ServiceInterfaceMock_Encrypt_Call {
	return &ServiceInterfaceMock_Encrypt_Call{Call: _e.mock.On("Encrypt", payload, recipientPublicKey, alg, enc)}
}

func (_c *ServiceInterfaceMock_Encrypt_Call) Run(run func(payload []byte, recipientPublicKey crypto.PublicKey, alg jwe.KeyEncAlgorithm, enc jwe.ContentEncAlgorithm)) *ServiceInterfaceMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 crypto.PublicKey
		if args[1] != nil {
			arg1 = args[1].(crypto.PublicKey)
		}
		var arg2 jwe.KeyEncAlgorithm
		if args[2] != nil {
			arg2 = args[2].(jwe.KeyEncAlgorithm)
		}
		var arg3 jwe.ContentEncAlgorithm
		if args[3] != nil {
			arg3 = args[3].(jwe.ContentEncAlgorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ServiceInterfaceMock_Encrypt_Call) Return(s string, serviceError *serviceerror.ServiceError) *ServiceInterfaceMock_Encrypt_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *ServiceInterfaceMock_Encrypt_Call) RunAndReturn(run func(payload []byte, recipientPublicKey crypto.PublicKey, alg jwe.KeyEncAlgorithm, enc jwe.ContentEncAlgorithm) (string, *serviceerror.ServiceError)) *ServiceInterfaceMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
