// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webauthnmock

import (
	"github.com/asgardeo/thunder/internal/authn/common"
	"github.com/asgardeo/thunder/internal/authn/webauthn"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewWebAuthnAuthnServiceInterfaceMock creates a new instance of WebAuthnAuthnServiceInterfaceMock.
func NewWebAuthnAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebAuthnAuthnServiceInterfaceMock {
	mockInstance := &WebAuthnAuthnServiceInterfaceMock{}
	mockInstance.Mock.Test(t)
	t.Cleanup(func() { mockInstance.AssertExpectations(t) })
	return mockInstance
}

// WebAuthnAuthnServiceInterfaceMock is an autogenerated mock type for the WebAuthnAuthnServiceInterface type
type WebAuthnAuthnServiceInterfaceMock struct {
	mock.Mock
}

// StartRegistration provides a mock function for StartRegistration
func (_m *WebAuthnAuthnServiceInterfaceMock) StartRegistration(req *webauthn.WebAuthnRegisterStartRequest) (*webauthn.WebAuthnRegisterStartData, *serviceerror.ServiceError) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for StartRegistration")
	}

	var r0 *webauthn.WebAuthnRegisterStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*webauthn.WebAuthnRegisterStartRequest) (*webauthn.WebAuthnRegisterStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*webauthn.WebAuthnRegisterStartRequest) *webauthn.WebAuthnRegisterStartData); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthn.WebAuthnRegisterStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*webauthn.WebAuthnRegisterStartRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// FinishRegistration provides a mock function for FinishRegistration
func (_m *WebAuthnAuthnServiceInterfaceMock) FinishRegistration(req *webauthn.WebAuthnRegisterFinishRequest) (*webauthn.WebAuthnRegisterFinishData, *serviceerror.ServiceError) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FinishRegistration")
	}

	var r0 *webauthn.WebAuthnRegisterFinishData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*webauthn.WebAuthnRegisterFinishRequest) (*webauthn.WebAuthnRegisterFinishData, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*webauthn.WebAuthnRegisterFinishRequest) *webauthn.WebAuthnRegisterFinishData); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthn.WebAuthnRegisterFinishData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*webauthn.WebAuthnRegisterFinishRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// StartAuthentication provides a mock function for StartAuthentication
func (_m *WebAuthnAuthnServiceInterfaceMock) StartAuthentication(userID, relyingPartyID string) (*webauthn.WebAuthnStartData, *serviceerror.ServiceError) {
	ret := _m.Called(userID, relyingPartyID)

	if len(ret) == 0 {
		panic("no return value specified for StartAuthentication")
	}

	var r0 *webauthn.WebAuthnStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) (*webauthn.WebAuthnStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(userID, relyingPartyID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *webauthn.WebAuthnStartData); ok {
		r0 = returnFunc(userID, relyingPartyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthn.WebAuthnStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(userID, relyingPartyID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// FinishAuthentication provides a mock function for FinishAuthentication
func (_m *WebAuthnAuthnServiceInterfaceMock) FinishAuthentication(credentialID, credentialType, clientDataJSON, authenticatorData, signature, userHandle, sessionToken string, skipAssertion bool, existingAssertion string) (*common.AuthenticationResponse, *serviceerror.ServiceError) {
	ret := _m.Called(credentialID, credentialType, clientDataJSON, authenticatorData, signature, userHandle, sessionToken, skipAssertion, existingAssertion)

	if len(ret) == 0 {
		panic("no return value specified for FinishAuthentication")
	}

	var r0 *common.AuthenticationResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, string, string, bool, string) (*common.AuthenticationResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(credentialID, credentialType, clientDataJSON, authenticatorData, signature, userHandle, sessionToken, skipAssertion, existingAssertion)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, string, string, bool, string) *common.AuthenticationResponse); ok {
		r0 = returnFunc(credentialID, credentialType, clientDataJSON, authenticatorData, signature, userHandle, sessionToken, skipAssertion, existingAssertion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthenticationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string, string, string, bool, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(credentialID, credentialType, clientDataJSON, authenticatorData, signature, userHandle, sessionToken, skipAssertion, existingAssertion)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}
