// Code generated by mockery v2.53.4. DO NOT EDIT.

package jwks

import (
	model "github.com/asgardeo/thunder/internal/oauth/jwks/model"
	serviceerror "github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// MockJWKSServiceInterface is an autogenerated mock type for the JWKSServiceInterface type
type MockJWKSServiceInterface struct {
	mock.Mock
}

type MockJWKSServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWKSServiceInterface) EXPECT() *MockJWKSServiceInterface_Expecter {
	return &MockJWKSServiceInterface_Expecter{mock: &_m.Mock}
}

// GetJWKS provides a mock function with no fields
func (_m *MockJWKSServiceInterface) GetJWKS() (*model.JWKSResponse, *serviceerror.ServiceError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJWKS")
	}

	var r0 *model.JWKSResponse
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func() (*model.JWKSResponse, *serviceerror.ServiceError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.JWKSResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.JWKSResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() *serviceerror.ServiceError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockJWKSServiceInterface_GetJWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJWKS'
type MockJWKSServiceInterface_GetJWKS_Call struct {
	*mock.Call
}

// GetJWKS is a helper method to define mock.On call
func (_e *MockJWKSServiceInterface_Expecter) GetJWKS() *MockJWKSServiceInterface_GetJWKS_Call {
	return &MockJWKSServiceInterface_GetJWKS_Call{Call: _e.mock.On("GetJWKS")}
}

func (_c *MockJWKSServiceInterface_GetJWKS_Call) Run(run func()) *MockJWKSServiceInterface_GetJWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJWKSServiceInterface_GetJWKS_Call) Return(_a0 *model.JWKSResponse, _a1 *serviceerror.ServiceError) *MockJWKSServiceInterface_GetJWKS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWKSServiceInterface_GetJWKS_Call) RunAndReturn(run func() (*model.JWKSResponse, *serviceerror.ServiceError)) *MockJWKSServiceInterface_GetJWKS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWKSServiceInterface creates a new instance of MockJWKSServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWKSServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWKSServiceInterface {
	mock := &MockJWKSServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
