// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resource

import (
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewResourceServiceInterfaceMock creates a new instance of ResourceServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceServiceInterfaceMock {
	mock := &ResourceServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceServiceInterfaceMock is an autogenerated mock type for the ResourceServiceInterface type
type ResourceServiceInterfaceMock struct {
	mock.Mock
}

type ResourceServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceServiceInterfaceMock) EXPECT() *ResourceServiceInterfaceMock_Expecter {
	return &ResourceServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateActionAtResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateActionAtResource(resourceServerID string, resourceID string, action Action) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, resourceID, action)

	if len(ret) == 0 {
		panic("no return value specified for CreateActionAtResource")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, Action) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, resourceID, action)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, Action) *Action); ok {
		r0 = returnFunc(resourceServerID, resourceID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, Action) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, resourceID, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateActionAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActionAtResource'
type ResourceServiceInterfaceMock_CreateActionAtResource_Call struct {
	*mock.Call
}

// CreateActionAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - action Action
func (_e *ResourceServiceInterfaceMock_Expecter) CreateActionAtResource(resourceServerID interface{}, resourceID interface{}, action interface{}) *ResourceServiceInterfaceMock_CreateActionAtResource_Call {
	return &ResourceServiceInterfaceMock_CreateActionAtResource_Call{Call: _e.mock.On("CreateActionAtResource", resourceServerID, resourceID, action)}
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResource_Call) Run(run func(resourceServerID string, resourceID string, action Action)) *ResourceServiceInterfaceMock_CreateActionAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Action
		if args[2] != nil {
			arg2 = args[2].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResource_Call) Return(action1 *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_CreateActionAtResource_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, action Action) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_CreateActionAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateActionAtResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateActionAtResourceServer(resourceServerID string, action Action) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, action)

	if len(ret) == 0 {
		panic("no return value specified for CreateActionAtResourceServer")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, Action) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, action)
	}
	if returnFunc, ok := ret.Get(0).(func(string, Action) *Action); ok {
		r0 = returnFunc(resourceServerID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, Action) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActionAtResourceServer'
type ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call struct {
	*mock.Call
}

// CreateActionAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - action Action
func (_e *ResourceServiceInterfaceMock_Expecter) CreateActionAtResourceServer(resourceServerID interface{}, action interface{}) *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call {
	return &ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call{Call: _e.mock.On("CreateActionAtResourceServer", resourceServerID, action)}
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call) Run(run func(resourceServerID string, action Action)) *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Action
		if args[1] != nil {
			arg1 = args[1].(Action)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call) Return(action1 *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, action Action) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_CreateActionAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateResource(resourceServerID string, res Resource) (*Resource, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, res)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 *Resource
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, Resource) (*Resource, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, res)
	}
	if returnFunc, ok := ret.Get(0).(func(string, Resource) *Resource); ok {
		r0 = returnFunc(resourceServerID, res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, Resource) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, res)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type ResourceServiceInterfaceMock_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - resourceServerID string
//   - res Resource
func (_e *ResourceServiceInterfaceMock_Expecter) CreateResource(resourceServerID interface{}, res interface{}) *ResourceServiceInterfaceMock_CreateResource_Call {
	return &ResourceServiceInterfaceMock_CreateResource_Call{Call: _e.mock.On("CreateResource", resourceServerID, res)}
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) Run(run func(resourceServerID string, res Resource)) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Resource
		if args[1] != nil {
			arg1 = args[1].(Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) Return(resource *Resource, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Return(resource, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResource_Call) RunAndReturn(run func(resourceServerID string, res Resource) (*Resource, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) CreateResourceServer(rs ResourceServer) (*ResourceServer, *serviceerror.ServiceError) {
	ret := _mock.Called(rs)

	if len(ret) == 0 {
		panic("no return value specified for CreateResourceServer")
	}

	var r0 *ResourceServer
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(ResourceServer) (*ResourceServer, *serviceerror.ServiceError)); ok {
		return returnFunc(rs)
	}
	if returnFunc, ok := ret.Get(0).(func(ResourceServer) *ResourceServer); ok {
		r0 = returnFunc(rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ResourceServer) *serviceerror.ServiceError); ok {
		r1 = returnFunc(rs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_CreateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResourceServer'
type ResourceServiceInterfaceMock_CreateResourceServer_Call struct {
	*mock.Call
}

// CreateResourceServer is a helper method to define mock.On call
//   - rs ResourceServer
func (_e *ResourceServiceInterfaceMock_Expecter) CreateResourceServer(rs interface{}) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	return &ResourceServiceInterfaceMock_CreateResourceServer_Call{Call: _e.mock.On("CreateResourceServer", rs)}
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) Run(run func(rs ResourceServer)) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ResourceServer
		if args[0] != nil {
			arg0 = args[0].(ResourceServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) Return(resourceServer *ResourceServer, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_CreateResourceServer_Call) RunAndReturn(run func(rs ResourceServer) (*ResourceServer, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActionAtResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteActionAtResource(resourceServerID string, resourceID string, id string) *serviceerror.ServiceError {
	ret := _mock.Called(resourceServerID, resourceID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActionAtResource")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(resourceServerID, resourceID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteActionAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActionAtResource'
type ResourceServiceInterfaceMock_DeleteActionAtResource_Call struct {
	*mock.Call
}

// DeleteActionAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteActionAtResource(resourceServerID interface{}, resourceID interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteActionAtResource_Call {
	return &ResourceServiceInterfaceMock_DeleteActionAtResource_Call{Call: _e.mock.On("DeleteActionAtResource", resourceServerID, resourceID, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResource_Call) Run(run func(resourceServerID string, resourceID string, id string)) *ResourceServiceInterfaceMock_DeleteActionAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResource_Call) Return(serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteActionAtResource_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, id string) *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteActionAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActionAtResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteActionAtResourceServer(resourceServerID string, id string) *serviceerror.ServiceError {
	ret := _mock.Called(resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActionAtResourceServer")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActionAtResourceServer'
type ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call struct {
	*mock.Call
}

// DeleteActionAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteActionAtResourceServer(resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call {
	return &ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call{Call: _e.mock.On("DeleteActionAtResourceServer", resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call) Run(run func(resourceServerID string, id string)) *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call) Return(serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, id string) *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteActionAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteResource(resourceServerID string, id string) *serviceerror.ServiceError {
	ret := _mock.Called(resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type ResourceServiceInterfaceMock_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteResource(resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_DeleteResource_Call {
	return &ResourceServiceInterfaceMock_DeleteResource_Call{Call: _e.mock.On("DeleteResource", resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) Run(run func(resourceServerID string, id string)) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) Return(serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResource_Call) RunAndReturn(run func(resourceServerID string, id string) *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) DeleteResourceServer(id string) *serviceerror.ServiceError {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResourceServer")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// ResourceServiceInterfaceMock_DeleteResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResourceServer'
type ResourceServiceInterfaceMock_DeleteResourceServer_Call struct {
	*mock.Call
}

// DeleteResourceServer is a helper method to define mock.On call
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) DeleteResourceServer(id interface{}) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	return &ResourceServiceInterfaceMock_DeleteResourceServer_Call{Call: _e.mock.On("DeleteResourceServer", id)}
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) Run(run func(id string)) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) Return(serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_DeleteResourceServer_Call) RunAndReturn(run func(id string) *serviceerror.ServiceError) *ResourceServiceInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionAtResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetActionAtResource(resourceServerID string, resourceID string, id string) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, resourceID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActionAtResource")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, resourceID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *Action); ok {
		r0 = returnFunc(resourceServerID, resourceID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, resourceID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetActionAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionAtResource'
type ResourceServiceInterfaceMock_GetActionAtResource_Call struct {
	*mock.Call
}

// GetActionAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetActionAtResource(resourceServerID interface{}, resourceID interface{}, id interface{}) *ResourceServiceInterfaceMock_GetActionAtResource_Call {
	return &ResourceServiceInterfaceMock_GetActionAtResource_Call{Call: _e.mock.On("GetActionAtResource", resourceServerID, resourceID, id)}
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResource_Call) Run(run func(resourceServerID string, resourceID string, id string)) *ResourceServiceInterfaceMock_GetActionAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResource_Call) Return(action *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetActionAtResource_Call {
	_c.Call.Return(action, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, id string) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetActionAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionAtResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetActionAtResourceServer(resourceServerID string, id string) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActionAtResourceServer")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *Action); ok {
		r0 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetActionAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionAtResourceServer'
type ResourceServiceInterfaceMock_GetActionAtResourceServer_Call struct {
	*mock.Call
}

// GetActionAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetActionAtResourceServer(resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call {
	return &ResourceServiceInterfaceMock_GetActionAtResourceServer_Call{Call: _e.mock.On("GetActionAtResourceServer", resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call) Run(run func(resourceServerID string, id string)) *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call) Return(action *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call {
	_c.Call.Return(action, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, id string) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetActionAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListAtResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetActionListAtResource(resourceServerID string, resourceID string, limit int, offset int) (*ActionList, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, resourceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListAtResource")
	}

	var r0 *ActionList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) (*ActionList, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, resourceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) *ActionList); ok {
		r0 = returnFunc(resourceServerID, resourceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ActionList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, resourceID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetActionListAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListAtResource'
type ResourceServiceInterfaceMock_GetActionListAtResource_Call struct {
	*mock.Call
}

// GetActionListAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetActionListAtResource(resourceServerID interface{}, resourceID interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetActionListAtResource_Call {
	return &ResourceServiceInterfaceMock_GetActionListAtResource_Call{Call: _e.mock.On("GetActionListAtResource", resourceServerID, resourceID, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResource_Call) Run(run func(resourceServerID string, resourceID string, limit int, offset int)) *ResourceServiceInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResource_Call) Return(actionList *ActionList, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Return(actionList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, limit int, offset int) (*ActionList, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListAtResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetActionListAtResourceServer(resourceServerID string, limit int, offset int) (*ActionList, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListAtResourceServer")
	}

	var r0 *ActionList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, int, int) (*ActionList, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) *ActionList); ok {
		r0 = returnFunc(resourceServerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ActionList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListAtResourceServer'
type ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call struct {
	*mock.Call
}

// GetActionListAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetActionListAtResourceServer(resourceServerID interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call {
	return &ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call{Call: _e.mock.On("GetActionListAtResourceServer", resourceServerID, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call) Run(run func(resourceServerID string, limit int, offset int)) *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call) Return(actionList *ActionList, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Return(actionList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, limit int, offset int) (*ActionList, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResource(resourceServerID string, id string) (*Resource, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *Resource
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) (*Resource, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *Resource); ok {
		r0 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type ResourceServiceInterfaceMock_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResource(resourceServerID interface{}, id interface{}) *ResourceServiceInterfaceMock_GetResource_Call {
	return &ResourceServiceInterfaceMock_GetResource_Call{Call: _e.mock.On("GetResource", resourceServerID, id)}
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) Run(run func(resourceServerID string, id string)) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) Return(resource *Resource, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Return(resource, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResource_Call) RunAndReturn(run func(resourceServerID string, id string) (*Resource, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceList(resourceServerID string, parentID *string, limit int, offset int) (*ResourceList, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, parentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceList")
	}

	var r0 *ResourceList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, *string, int, int) (*ResourceList, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, parentID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string, int, int) *ResourceList); ok {
		r0 = returnFunc(resourceServerID, parentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string, int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, parentID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceList'
type ResourceServiceInterfaceMock_GetResourceList_Call struct {
	*mock.Call
}

// GetResourceList is a helper method to define mock.On call
//   - resourceServerID string
//   - parentID *string
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceList(resourceServerID interface{}, parentID interface{}, limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetResourceList_Call {
	return &ResourceServiceInterfaceMock_GetResourceList_Call{Call: _e.mock.On("GetResourceList", resourceServerID, parentID, limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) Run(run func(resourceServerID string, parentID *string, limit int, offset int)) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) Return(resourceList *ResourceList, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Return(resourceList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceList_Call) RunAndReturn(run func(resourceServerID string, parentID *string, limit int, offset int) (*ResourceList, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetResourceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServer(id string) (*ResourceServer, *serviceerror.ServiceError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServer")
	}

	var r0 *ResourceServer
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*ResourceServer, *serviceerror.ServiceError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ResourceServer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServer'
type ResourceServiceInterfaceMock_GetResourceServer_Call struct {
	*mock.Call
}

// GetResourceServer is a helper method to define mock.On call
//   - id string
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServer(id interface{}) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	return &ResourceServiceInterfaceMock_GetResourceServer_Call{Call: _e.mock.On("GetResourceServer", id)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) Run(run func(id string)) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) Return(resourceServer *ResourceServer, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServer_Call) RunAndReturn(run func(id string) (*ResourceServer, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerList provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) GetResourceServerList(limit int, offset int) (*ResourceServerList, *serviceerror.ServiceError) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerList")
	}

	var r0 *ResourceServerList
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(int, int) (*ResourceServerList, *serviceerror.ServiceError)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) *ResourceServerList); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceServerList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_GetResourceServerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerList'
type ResourceServiceInterfaceMock_GetResourceServerList_Call struct {
	*mock.Call
}

// GetResourceServerList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *ResourceServiceInterfaceMock_Expecter) GetResourceServerList(limit interface{}, offset interface{}) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	return &ResourceServiceInterfaceMock_GetResourceServerList_Call{Call: _e.mock.On("GetResourceServerList", limit, offset)}
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) Run(run func(limit int, offset int)) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) Return(resourceServerList *ResourceServerList, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(resourceServerList, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_GetResourceServerList_Call) RunAndReturn(run func(limit int, offset int) (*ResourceServerList, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActionAtResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateActionAtResource(resourceServerID string, resourceID string, id string, action Action) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, resourceID, id, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActionAtResource")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, string, Action) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, resourceID, id, action)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, Action) *Action); ok {
		r0 = returnFunc(resourceServerID, resourceID, id, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, Action) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, resourceID, id, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateActionAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActionAtResource'
type ResourceServiceInterfaceMock_UpdateActionAtResource_Call struct {
	*mock.Call
}

// UpdateActionAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - id string
//   - action Action
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateActionAtResource(resourceServerID interface{}, resourceID interface{}, id interface{}, action interface{}) *ResourceServiceInterfaceMock_UpdateActionAtResource_Call {
	return &ResourceServiceInterfaceMock_UpdateActionAtResource_Call{Call: _e.mock.On("UpdateActionAtResource", resourceServerID, resourceID, id, action)}
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResource_Call) Run(run func(resourceServerID string, resourceID string, id string, action Action)) *ResourceServiceInterfaceMock_UpdateActionAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 Action
		if args[3] != nil {
			arg3 = args[3].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResource_Call) Return(action1 *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_UpdateActionAtResource_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, id string, action Action) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_UpdateActionAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActionAtResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateActionAtResourceServer(resourceServerID string, id string, action Action) (*Action, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, id, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActionAtResourceServer")
	}

	var r0 *Action
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, Action) (*Action, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, id, action)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, Action) *Action); ok {
		r0 = returnFunc(resourceServerID, id, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, Action) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, id, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActionAtResourceServer'
type ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call struct {
	*mock.Call
}

// UpdateActionAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
//   - action Action
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateActionAtResourceServer(resourceServerID interface{}, id interface{}, action interface{}) *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call {
	return &ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call{Call: _e.mock.On("UpdateActionAtResourceServer", resourceServerID, id, action)}
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call) Run(run func(resourceServerID string, id string, action Action)) *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Action
		if args[2] != nil {
			arg2 = args[2].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call) Return(action1 *Action, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call {
	_c.Call.Return(action1, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, id string, action Action) (*Action, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_UpdateActionAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateResource(resourceServerID string, id string, res Resource) (*Resource, *serviceerror.ServiceError) {
	ret := _mock.Called(resourceServerID, id, res)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *Resource
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, Resource) (*Resource, *serviceerror.ServiceError)); ok {
		return returnFunc(resourceServerID, id, res)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, Resource) *Resource); ok {
		r0 = returnFunc(resourceServerID, id, res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, Resource) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resourceServerID, id, res)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type ResourceServiceInterfaceMock_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - resourceServerID string
//   - id string
//   - res Resource
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateResource(resourceServerID interface{}, id interface{}, res interface{}) *ResourceServiceInterfaceMock_UpdateResource_Call {
	return &ResourceServiceInterfaceMock_UpdateResource_Call{Call: _e.mock.On("UpdateResource", resourceServerID, id, res)}
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) Run(run func(resourceServerID string, id string, res Resource)) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Resource
		if args[2] != nil {
			arg2 = args[2].(Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) Return(resource *Resource, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Return(resource, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResource_Call) RunAndReturn(run func(resourceServerID string, id string, res Resource) (*Resource, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceServer provides a mock function for the type ResourceServiceInterfaceMock
func (_mock *ResourceServiceInterfaceMock) UpdateResourceServer(id string, rs ResourceServer) (*ResourceServer, *serviceerror.ServiceError) {
	ret := _mock.Called(id, rs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceServer")
	}

	var r0 *ResourceServer
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, ResourceServer) (*ResourceServer, *serviceerror.ServiceError)); ok {
		return returnFunc(id, rs)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ResourceServer) *ResourceServer); ok {
		r0 = returnFunc(id, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ResourceServer) *serviceerror.ServiceError); ok {
		r1 = returnFunc(id, rs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ResourceServiceInterfaceMock_UpdateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceServer'
type ResourceServiceInterfaceMock_UpdateResourceServer_Call struct {
	*mock.Call
}

// UpdateResourceServer is a helper method to define mock.On call
//   - id string
//   - rs ResourceServer
func (_e *ResourceServiceInterfaceMock_Expecter) UpdateResourceServer(id interface{}, rs interface{}) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	return &ResourceServiceInterfaceMock_UpdateResourceServer_Call{Call: _e.mock.On("UpdateResourceServer", id, rs)}
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) Run(run func(id string, rs ResourceServer)) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 ResourceServer
		if args[1] != nil {
			arg1 = args[1].(ResourceServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) Return(resourceServer *ResourceServer, serviceError *serviceerror.ServiceError) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(resourceServer, serviceError)
	return _c
}

func (_c *ResourceServiceInterfaceMock_UpdateResourceServer_Call) RunAndReturn(run func(id string, rs ResourceServer) (*ResourceServer, *serviceerror.ServiceError)) *ResourceServiceInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}
