// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resource

import (
	mock "github.com/stretchr/testify/mock"
)

// newResourceStoreInterfaceMock creates a new instance of resourceStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newResourceStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *resourceStoreInterfaceMock {
	mock := &resourceStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// resourceStoreInterfaceMock is an autogenerated mock type for the resourceStoreInterface type
type resourceStoreInterfaceMock struct {
	mock.Mock
}

type resourceStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *resourceStoreInterfaceMock) EXPECT() *resourceStoreInterfaceMock_Expecter {
	return &resourceStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CheckActionHandleExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckActionHandleExists(resourceServerID string, resourceID *string, handle string) (bool, error) {
	ret := _mock.Called(resourceServerID, resourceID, handle)

	if len(ret) == 0 {
		panic("no return value specified for CheckActionHandleExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *string, string) (bool, error)); ok {
		return returnFunc(resourceServerID, resourceID, handle)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string, string) bool); ok {
		r0 = returnFunc(resourceServerID, resourceID, handle)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string, string) error); ok {
		r1 = returnFunc(resourceServerID, resourceID, handle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckActionHandleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckActionHandleExists'
type resourceStoreInterfaceMock_CheckActionHandleExists_Call struct {
	*mock.Call
}

// CheckActionHandleExists is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID *string
//   - handle string
func (_e *resourceStoreInterfaceMock_Expecter) CheckActionHandleExists(resourceServerID interface{}, resourceID interface{}, handle interface{}) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	return &resourceStoreInterfaceMock_CheckActionHandleExists_Call{Call: _e.mock.On("CheckActionHandleExists", resourceServerID, resourceID, handle)}
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) Run(run func(resourceServerID string, resourceID *string, handle string)) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) RunAndReturn(run func(resourceServerID string, resourceID *string, handle string) (bool, error)) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckCircularDependency provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckCircularDependency(resourceID string, newParentID string) (bool, error) {
	ret := _mock.Called(resourceID, newParentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckCircularDependency")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(resourceID, newParentID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(resourceID, newParentID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(resourceID, newParentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckCircularDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCircularDependency'
type resourceStoreInterfaceMock_CheckCircularDependency_Call struct {
	*mock.Call
}

// CheckCircularDependency is a helper method to define mock.On call
//   - resourceID string
//   - newParentID string
func (_e *resourceStoreInterfaceMock_Expecter) CheckCircularDependency(resourceID interface{}, newParentID interface{}) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	return &resourceStoreInterfaceMock_CheckCircularDependency_Call{Call: _e.mock.On("CheckCircularDependency", resourceID, newParentID)}
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) Run(run func(resourceID string, newParentID string)) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) RunAndReturn(run func(resourceID string, newParentID string) (bool, error)) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceExistAndGetInternalID provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceExistAndGetInternalID(uuid string, resourceServerUUID string) (int, error) {
	ret := _mock.Called(uuid, resourceServerUUID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceExistAndGetInternalID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return returnFunc(uuid, resourceServerUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = returnFunc(uuid, resourceServerUUID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uuid, resourceServerUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceExistAndGetInternalID'
type resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call struct {
	*mock.Call
}

// CheckResourceExistAndGetInternalID is a helper method to define mock.On call
//   - uuid string
//   - resourceServerUUID string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceExistAndGetInternalID(uuid interface{}, resourceServerUUID interface{}) *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call {
	return &resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call{Call: _e.mock.On("CheckResourceExistAndGetInternalID", uuid, resourceServerUUID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call) Run(run func(uuid string, resourceServerUUID string)) *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call) Return(n int, err error) *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call) RunAndReturn(run func(uuid string, resourceServerUUID string) (int, error)) *resourceStoreInterfaceMock_CheckResourceExistAndGetInternalID_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceHandleExistsUnderParent provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceHandleExistsUnderParent(resourceServerID string, handle string, parentID *string) (bool, error) {
	ret := _mock.Called(resourceServerID, handle, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceHandleExistsUnderParent")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (bool, error)); ok {
		return returnFunc(resourceServerID, handle, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) bool); ok {
		r0 = returnFunc(resourceServerID, handle, parentID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(resourceServerID, handle, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceHandleExistsUnderParent'
type resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call struct {
	*mock.Call
}

// CheckResourceHandleExistsUnderParent is a helper method to define mock.On call
//   - resourceServerID string
//   - handle string
//   - parentID *string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceHandleExistsUnderParent(resourceServerID interface{}, handle interface{}, parentID interface{}) *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call {
	return &resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call{Call: _e.mock.On("CheckResourceHandleExistsUnderParent", resourceServerID, handle, parentID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call) Run(run func(resourceServerID string, handle string, parentID *string)) *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call) RunAndReturn(run func(resourceServerID string, handle string, parentID *string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceHandleExistsUnderParent_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceHasDependencies provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceHasDependencies(id string) (bool, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceHasDependencies")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceHasDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceHasDependencies'
type resourceStoreInterfaceMock_CheckResourceHasDependencies_Call struct {
	*mock.Call
}

// CheckResourceHasDependencies is a helper method to define mock.On call
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceHasDependencies(id interface{}) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	return &resourceStoreInterfaceMock_CheckResourceHasDependencies_Call{Call: _e.mock.On("CheckResourceHasDependencies", id)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) Run(run func(id string)) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) RunAndReturn(run func(id string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerExistAndGetInternalID provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerExistAndGetInternalID(uuid string) (int, error) {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerExistAndGetInternalID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerExistAndGetInternalID'
type resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call struct {
	*mock.Call
}

// CheckResourceServerExistAndGetInternalID is a helper method to define mock.On call
//   - uuid string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerExistAndGetInternalID(uuid interface{}) *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call{Call: _e.mock.On("CheckResourceServerExistAndGetInternalID", uuid)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call) Run(run func(uuid string)) *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call) Return(n int, err error) *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call) RunAndReturn(run func(uuid string) (int, error)) *resourceStoreInterfaceMock_CheckResourceServerExistAndGetInternalID_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerHasDependencies provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerHasDependencies(id string) (bool, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerHasDependencies")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerHasDependencies'
type resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call struct {
	*mock.Call
}

// CheckResourceServerHasDependencies is a helper method to define mock.On call
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerHasDependencies(id interface{}) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call{Call: _e.mock.On("CheckResourceServerHasDependencies", id)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) Run(run func(id string)) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) RunAndReturn(run func(id string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerIdentifierExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerIdentifierExists(identifier string) (bool, error) {
	ret := _mock.Called(identifier)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerIdentifierExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(identifier)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerIdentifierExists'
type resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call struct {
	*mock.Call
}

// CheckResourceServerIdentifierExists is a helper method to define mock.On call
//   - identifier string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerIdentifierExists(identifier interface{}) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call{Call: _e.mock.On("CheckResourceServerIdentifierExists", identifier)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) Run(run func(identifier string)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) RunAndReturn(run func(identifier string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerIdentifierExistsExcludingID provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerIdentifierExistsExcludingID(identifier string, excludeID string) (bool, error) {
	ret := _mock.Called(identifier, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerIdentifierExistsExcludingID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(identifier, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(identifier, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(identifier, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerIdentifierExistsExcludingID'
type resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call struct {
	*mock.Call
}

// CheckResourceServerIdentifierExistsExcludingID is a helper method to define mock.On call
//   - identifier string
//   - excludeID string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerIdentifierExistsExcludingID(identifier interface{}, excludeID interface{}) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call{Call: _e.mock.On("CheckResourceServerIdentifierExistsExcludingID", identifier, excludeID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call) Run(run func(identifier string, excludeID string)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call) RunAndReturn(run func(identifier string, excludeID string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExistsExcludingID_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerNameExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerNameExists(name string) (bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerNameExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerNameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerNameExists'
type resourceStoreInterfaceMock_CheckResourceServerNameExists_Call struct {
	*mock.Call
}

// CheckResourceServerNameExists is a helper method to define mock.On call
//   - name string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerNameExists(name interface{}) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerNameExists_Call{Call: _e.mock.On("CheckResourceServerNameExists", name)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) Run(run func(name string)) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) RunAndReturn(run func(name string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerNameExistsExcludingID provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerNameExistsExcludingID(name string, excludeID string) (bool, error) {
	ret := _mock.Called(name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerNameExistsExcludingID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(name, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(name, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerNameExistsExcludingID'
type resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call struct {
	*mock.Call
}

// CheckResourceServerNameExistsExcludingID is a helper method to define mock.On call
//   - name string
//   - excludeID string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerNameExistsExcludingID(name interface{}, excludeID interface{}) *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call{Call: _e.mock.On("CheckResourceServerNameExistsExcludingID", name, excludeID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call) Run(run func(name string, excludeID string)) *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call) RunAndReturn(run func(name string, excludeID string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerNameExistsExcludingID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateAction(uuid string, resourceServerInternalID int, resourceInternalID *int, action Action) error {
	ret := _mock.Called(uuid, resourceServerInternalID, resourceInternalID, action)

	if len(ret) == 0 {
		panic("no return value specified for CreateAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, *int, Action) error); ok {
		r0 = returnFunc(uuid, resourceServerInternalID, resourceInternalID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAction'
type resourceStoreInterfaceMock_CreateAction_Call struct {
	*mock.Call
}

// CreateAction is a helper method to define mock.On call
//   - uuid string
//   - resourceServerInternalID int
//   - resourceInternalID *int
//   - action Action
func (_e *resourceStoreInterfaceMock_Expecter) CreateAction(uuid interface{}, resourceServerInternalID interface{}, resourceInternalID interface{}, action interface{}) *resourceStoreInterfaceMock_CreateAction_Call {
	return &resourceStoreInterfaceMock_CreateAction_Call{Call: _e.mock.On("CreateAction", uuid, resourceServerInternalID, resourceInternalID, action)}
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) Run(run func(uuid string, resourceServerInternalID int, resourceInternalID *int, action Action)) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 Action
		if args[3] != nil {
			arg3 = args[3].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) Return(err error) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) RunAndReturn(run func(uuid string, resourceServerInternalID int, resourceInternalID *int, action Action) error) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateResource(uuid string, resourceServerInternalID int, parentInternalID *int, res Resource) error {
	ret := _mock.Called(uuid, resourceServerInternalID, parentInternalID, res)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, *int, Resource) error); ok {
		r0 = returnFunc(uuid, resourceServerInternalID, parentInternalID, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type resourceStoreInterfaceMock_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - uuid string
//   - resourceServerInternalID int
//   - parentInternalID *int
//   - res Resource
func (_e *resourceStoreInterfaceMock_Expecter) CreateResource(uuid interface{}, resourceServerInternalID interface{}, parentInternalID interface{}, res interface{}) *resourceStoreInterfaceMock_CreateResource_Call {
	return &resourceStoreInterfaceMock_CreateResource_Call{Call: _e.mock.On("CreateResource", uuid, resourceServerInternalID, parentInternalID, res)}
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) Run(run func(uuid string, resourceServerInternalID int, parentInternalID *int, res Resource)) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 Resource
		if args[3] != nil {
			arg3 = args[3].(Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) Return(err error) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) RunAndReturn(run func(uuid string, resourceServerInternalID int, parentInternalID *int, res Resource) error) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateResourceServer(id string, rs ResourceServer) error {
	ret := _mock.Called(id, rs)

	if len(ret) == 0 {
		panic("no return value specified for CreateResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ResourceServer) error); ok {
		r0 = returnFunc(id, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResourceServer'
type resourceStoreInterfaceMock_CreateResourceServer_Call struct {
	*mock.Call
}

// CreateResourceServer is a helper method to define mock.On call
//   - id string
//   - rs ResourceServer
func (_e *resourceStoreInterfaceMock_Expecter) CreateResourceServer(id interface{}, rs interface{}) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	return &resourceStoreInterfaceMock_CreateResourceServer_Call{Call: _e.mock.On("CreateResourceServer", id, rs)}
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) Run(run func(id string, rs ResourceServer)) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 ResourceServer
		if args[1] != nil {
			arg1 = args[1].(ResourceServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) RunAndReturn(run func(id string, rs ResourceServer) error) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteAction(id string, resourceServerID string, resourceID *string) error {
	ret := _mock.Called(id, resourceServerID, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) error); ok {
		r0 = returnFunc(id, resourceServerID, resourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAction'
type resourceStoreInterfaceMock_DeleteAction_Call struct {
	*mock.Call
}

// DeleteAction is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
//   - resourceID *string
func (_e *resourceStoreInterfaceMock_Expecter) DeleteAction(id interface{}, resourceServerID interface{}, resourceID interface{}) *resourceStoreInterfaceMock_DeleteAction_Call {
	return &resourceStoreInterfaceMock_DeleteAction_Call{Call: _e.mock.On("DeleteAction", id, resourceServerID, resourceID)}
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) Run(run func(id string, resourceServerID string, resourceID *string)) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) Return(err error) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) RunAndReturn(run func(id string, resourceServerID string, resourceID *string) error) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteResource(id string, resourceServerID string) error {
	ret := _mock.Called(id, resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(id, resourceServerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type resourceStoreInterfaceMock_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
func (_e *resourceStoreInterfaceMock_Expecter) DeleteResource(id interface{}, resourceServerID interface{}) *resourceStoreInterfaceMock_DeleteResource_Call {
	return &resourceStoreInterfaceMock_DeleteResource_Call{Call: _e.mock.On("DeleteResource", id, resourceServerID)}
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) Run(run func(id string, resourceServerID string)) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) Return(err error) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) RunAndReturn(run func(id string, resourceServerID string) error) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteResourceServer(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResourceServer'
type resourceStoreInterfaceMock_DeleteResourceServer_Call struct {
	*mock.Call
}

// DeleteResourceServer is a helper method to define mock.On call
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) DeleteResourceServer(id interface{}) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	return &resourceStoreInterfaceMock_DeleteResourceServer_Call{Call: _e.mock.On("DeleteResourceServer", id)}
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) Run(run func(id string)) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) RunAndReturn(run func(id string) error) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetAction(id string, resourceServerID string, resourceID *string) (Action, error) {
	ret := _mock.Called(id, resourceServerID, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetAction")
	}

	var r0 Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (Action, error)); ok {
		return returnFunc(id, resourceServerID, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) Action); ok {
		r0 = returnFunc(id, resourceServerID, resourceID)
	} else {
		r0 = ret.Get(0).(Action)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, resourceServerID, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAction'
type resourceStoreInterfaceMock_GetAction_Call struct {
	*mock.Call
}

// GetAction is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
//   - resourceID *string
func (_e *resourceStoreInterfaceMock_Expecter) GetAction(id interface{}, resourceServerID interface{}, resourceID interface{}) *resourceStoreInterfaceMock_GetAction_Call {
	return &resourceStoreInterfaceMock_GetAction_Call{Call: _e.mock.On("GetAction", id, resourceServerID, resourceID)}
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) Run(run func(id string, resourceServerID string, resourceID *string)) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) Return(action Action, err error) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Return(action, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) RunAndReturn(run func(id string, resourceServerID string, resourceID *string) (Action, error)) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListAtResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionListAtResource(resourceServerID string, resourceID string, limit int, offset int) ([]Action, error) {
	ret := _mock.Called(resourceServerID, resourceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListAtResource")
	}

	var r0 []Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]Action, error)); ok {
		return returnFunc(resourceServerID, resourceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []Action); ok {
		r0 = returnFunc(resourceServerID, resourceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = returnFunc(resourceServerID, resourceID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionListAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListAtResource'
type resourceStoreInterfaceMock_GetActionListAtResource_Call struct {
	*mock.Call
}

// GetActionListAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetActionListAtResource(resourceServerID interface{}, resourceID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetActionListAtResource_Call {
	return &resourceStoreInterfaceMock_GetActionListAtResource_Call{Call: _e.mock.On("GetActionListAtResource", resourceServerID, resourceID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResource_Call) Run(run func(resourceServerID string, resourceID string, limit int, offset int)) *resourceStoreInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResource_Call) Return(actions []Action, err error) *resourceStoreInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Return(actions, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string, limit int, offset int) ([]Action, error)) *resourceStoreInterfaceMock_GetActionListAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListAtResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionListAtResourceServer(resourceServerID string, limit int, offset int) ([]Action, error) {
	ret := _mock.Called(resourceServerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListAtResourceServer")
	}

	var r0 []Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]Action, error)); ok {
		return returnFunc(resourceServerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []Action); ok {
		r0 = returnFunc(resourceServerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(resourceServerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionListAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListAtResourceServer'
type resourceStoreInterfaceMock_GetActionListAtResourceServer_Call struct {
	*mock.Call
}

// GetActionListAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetActionListAtResourceServer(resourceServerID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call {
	return &resourceStoreInterfaceMock_GetActionListAtResourceServer_Call{Call: _e.mock.On("GetActionListAtResourceServer", resourceServerID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call) Run(run func(resourceServerID string, limit int, offset int)) *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call) Return(actions []Action, err error) *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Return(actions, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call) RunAndReturn(run func(resourceServerID string, limit int, offset int) ([]Action, error)) *resourceStoreInterfaceMock_GetActionListAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListCountAtResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionListCountAtResource(resourceServerID string, resourceID string) (int, error) {
	ret := _mock.Called(resourceServerID, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListCountAtResource")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return returnFunc(resourceServerID, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = returnFunc(resourceServerID, resourceID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(resourceServerID, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionListCountAtResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListCountAtResource'
type resourceStoreInterfaceMock_GetActionListCountAtResource_Call struct {
	*mock.Call
}

// GetActionListCountAtResource is a helper method to define mock.On call
//   - resourceServerID string
//   - resourceID string
func (_e *resourceStoreInterfaceMock_Expecter) GetActionListCountAtResource(resourceServerID interface{}, resourceID interface{}) *resourceStoreInterfaceMock_GetActionListCountAtResource_Call {
	return &resourceStoreInterfaceMock_GetActionListCountAtResource_Call{Call: _e.mock.On("GetActionListCountAtResource", resourceServerID, resourceID)}
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResource_Call) Run(run func(resourceServerID string, resourceID string)) *resourceStoreInterfaceMock_GetActionListCountAtResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResource_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetActionListCountAtResource_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResource_Call) RunAndReturn(run func(resourceServerID string, resourceID string) (int, error)) *resourceStoreInterfaceMock_GetActionListCountAtResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListCountAtResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionListCountAtResourceServer(resourceServerID string) (int, error) {
	ret := _mock.Called(resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListCountAtResourceServer")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(resourceServerID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(resourceServerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListCountAtResourceServer'
type resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call struct {
	*mock.Call
}

// GetActionListCountAtResourceServer is a helper method to define mock.On call
//   - resourceServerID string
func (_e *resourceStoreInterfaceMock_Expecter) GetActionListCountAtResourceServer(resourceServerID interface{}) *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call {
	return &resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call{Call: _e.mock.On("GetActionListCountAtResourceServer", resourceServerID)}
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call) Run(run func(resourceServerID string)) *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call) RunAndReturn(run func(resourceServerID string) (int, error)) *resourceStoreInterfaceMock_GetActionListCountAtResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResource(id string, resourceServerID string) (Resource, error) {
	ret := _mock.Called(id, resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (Resource, error)); ok {
		return returnFunc(id, resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) Resource); ok {
		r0 = returnFunc(id, resourceServerID)
	} else {
		r0 = ret.Get(0).(Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(id, resourceServerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type resourceStoreInterfaceMock_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
func (_e *resourceStoreInterfaceMock_Expecter) GetResource(id interface{}, resourceServerID interface{}) *resourceStoreInterfaceMock_GetResource_Call {
	return &resourceStoreInterfaceMock_GetResource_Call{Call: _e.mock.On("GetResource", id, resourceServerID)}
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) Run(run func(id string, resourceServerID string)) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) Return(resource Resource, err error) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) RunAndReturn(run func(id string, resourceServerID string) (Resource, error)) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceList provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceList(resourceServerID string, limit int, offset int) ([]Resource, error) {
	ret := _mock.Called(resourceServerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceList")
	}

	var r0 []Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]Resource, error)); ok {
		return returnFunc(resourceServerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []Resource); ok {
		r0 = returnFunc(resourceServerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(resourceServerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceList'
type resourceStoreInterfaceMock_GetResourceList_Call struct {
	*mock.Call
}

// GetResourceList is a helper method to define mock.On call
//   - resourceServerID string
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceList(resourceServerID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceList_Call {
	return &resourceStoreInterfaceMock_GetResourceList_Call{Call: _e.mock.On("GetResourceList", resourceServerID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) Run(run func(resourceServerID string, limit int, offset int)) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) Return(resources []Resource, err error) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) RunAndReturn(run func(resourceServerID string, limit int, offset int) ([]Resource, error)) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListByParent provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListByParent(resourceServerID string, parentID *string, limit int, offset int) ([]Resource, error) {
	ret := _mock.Called(resourceServerID, parentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListByParent")
	}

	var r0 []Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *string, int, int) ([]Resource, error)); ok {
		return returnFunc(resourceServerID, parentID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string, int, int) []Resource); ok {
		r0 = returnFunc(resourceServerID, parentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string, int, int) error); ok {
		r1 = returnFunc(resourceServerID, parentID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListByParent'
type resourceStoreInterfaceMock_GetResourceListByParent_Call struct {
	*mock.Call
}

// GetResourceListByParent is a helper method to define mock.On call
//   - resourceServerID string
//   - parentID *string
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListByParent(resourceServerID interface{}, parentID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	return &resourceStoreInterfaceMock_GetResourceListByParent_Call{Call: _e.mock.On("GetResourceListByParent", resourceServerID, parentID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) Run(run func(resourceServerID string, parentID *string, limit int, offset int)) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) Return(resources []Resource, err error) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) RunAndReturn(run func(resourceServerID string, parentID *string, limit int, offset int) ([]Resource, error)) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListCount provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListCount(resourceServerID string) (int, error) {
	ret := _mock.Called(resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(resourceServerID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(resourceServerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListCount'
type resourceStoreInterfaceMock_GetResourceListCount_Call struct {
	*mock.Call
}

// GetResourceListCount is a helper method to define mock.On call
//   - resourceServerID string
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListCount(resourceServerID interface{}) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	return &resourceStoreInterfaceMock_GetResourceListCount_Call{Call: _e.mock.On("GetResourceListCount", resourceServerID)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) Run(run func(resourceServerID string)) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) RunAndReturn(run func(resourceServerID string) (int, error)) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListCountByParent provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListCountByParent(resourceServerID string, parentID *string) (int, error) {
	ret := _mock.Called(resourceServerID, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListCountByParent")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *string) (int, error)); ok {
		return returnFunc(resourceServerID, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string) int); ok {
		r0 = returnFunc(resourceServerID, parentID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string) error); ok {
		r1 = returnFunc(resourceServerID, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListCountByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListCountByParent'
type resourceStoreInterfaceMock_GetResourceListCountByParent_Call struct {
	*mock.Call
}

// GetResourceListCountByParent is a helper method to define mock.On call
//   - resourceServerID string
//   - parentID *string
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListCountByParent(resourceServerID interface{}, parentID interface{}) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	return &resourceStoreInterfaceMock_GetResourceListCountByParent_Call{Call: _e.mock.On("GetResourceListCountByParent", resourceServerID, parentID)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) Run(run func(resourceServerID string, parentID *string)) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) RunAndReturn(run func(resourceServerID string, parentID *string) (int, error)) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServer(id string) (ResourceServer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServer")
	}

	var r0 ResourceServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (ResourceServer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) ResourceServer); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(ResourceServer)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServer'
type resourceStoreInterfaceMock_GetResourceServer_Call struct {
	*mock.Call
}

// GetResourceServer is a helper method to define mock.On call
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServer(id interface{}) *resourceStoreInterfaceMock_GetResourceServer_Call {
	return &resourceStoreInterfaceMock_GetResourceServer_Call{Call: _e.mock.On("GetResourceServer", id)}
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) Run(run func(id string)) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) Return(resourceServer ResourceServer, err error) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(resourceServer, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) RunAndReturn(run func(id string) (ResourceServer, error)) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerList provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServerList(limit int, offset int) ([]ResourceServer, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerList")
	}

	var r0 []ResourceServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]ResourceServer, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []ResourceServer); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceServerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerList'
type resourceStoreInterfaceMock_GetResourceServerList_Call struct {
	*mock.Call
}

// GetResourceServerList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServerList(limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	return &resourceStoreInterfaceMock_GetResourceServerList_Call{Call: _e.mock.On("GetResourceServerList", limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) Run(run func(limit int, offset int)) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) Return(resourceServers []ResourceServer, err error) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(resourceServers, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) RunAndReturn(run func(limit int, offset int) ([]ResourceServer, error)) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerListCount provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServerListCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceServerListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerListCount'
type resourceStoreInterfaceMock_GetResourceServerListCount_Call struct {
	*mock.Call
}

// GetResourceServerListCount is a helper method to define mock.On call
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServerListCount() *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	return &resourceStoreInterfaceMock_GetResourceServerListCount_Call{Call: _e.mock.On("GetResourceServerListCount")}
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) Run(run func()) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) RunAndReturn(run func() (int, error)) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsActionExist provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) IsActionExist(id string, resourceServerID string, resourceID *string) (bool, error) {
	ret := _mock.Called(id, resourceServerID, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for IsActionExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (bool, error)); ok {
		return returnFunc(id, resourceServerID, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) bool); ok {
		r0 = returnFunc(id, resourceServerID, resourceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, resourceServerID, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_IsActionExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActionExist'
type resourceStoreInterfaceMock_IsActionExist_Call struct {
	*mock.Call
}

// IsActionExist is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
//   - resourceID *string
func (_e *resourceStoreInterfaceMock_Expecter) IsActionExist(id interface{}, resourceServerID interface{}, resourceID interface{}) *resourceStoreInterfaceMock_IsActionExist_Call {
	return &resourceStoreInterfaceMock_IsActionExist_Call{Call: _e.mock.On("IsActionExist", id, resourceServerID, resourceID)}
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) Run(run func(id string, resourceServerID string, resourceID *string)) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) Return(b bool, err error) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) RunAndReturn(run func(id string, resourceServerID string, resourceID *string) (bool, error)) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Return(run)
	return _c
}

// IsResourceExist provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) IsResourceExist(id string, resourceServerID string) (bool, error) {
	ret := _mock.Called(id, resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for IsResourceExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(id, resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(id, resourceServerID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(id, resourceServerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_IsResourceExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsResourceExist'
type resourceStoreInterfaceMock_IsResourceExist_Call struct {
	*mock.Call
}

// IsResourceExist is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
func (_e *resourceStoreInterfaceMock_Expecter) IsResourceExist(id interface{}, resourceServerID interface{}) *resourceStoreInterfaceMock_IsResourceExist_Call {
	return &resourceStoreInterfaceMock_IsResourceExist_Call{Call: _e.mock.On("IsResourceExist", id, resourceServerID)}
}

func (_c *resourceStoreInterfaceMock_IsResourceExist_Call) Run(run func(id string, resourceServerID string)) *resourceStoreInterfaceMock_IsResourceExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_IsResourceExist_Call) Return(b bool, err error) *resourceStoreInterfaceMock_IsResourceExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_IsResourceExist_Call) RunAndReturn(run func(id string, resourceServerID string) (bool, error)) *resourceStoreInterfaceMock_IsResourceExist_Call {
	_c.Call.Return(run)
	return _c
}

// IsResourceServerExist provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) IsResourceServerExist(id string) (bool, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsResourceServerExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_IsResourceServerExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsResourceServerExist'
type resourceStoreInterfaceMock_IsResourceServerExist_Call struct {
	*mock.Call
}

// IsResourceServerExist is a helper method to define mock.On call
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) IsResourceServerExist(id interface{}) *resourceStoreInterfaceMock_IsResourceServerExist_Call {
	return &resourceStoreInterfaceMock_IsResourceServerExist_Call{Call: _e.mock.On("IsResourceServerExist", id)}
}

func (_c *resourceStoreInterfaceMock_IsResourceServerExist_Call) Run(run func(id string)) *resourceStoreInterfaceMock_IsResourceServerExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_IsResourceServerExist_Call) Return(b bool, err error) *resourceStoreInterfaceMock_IsResourceServerExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_IsResourceServerExist_Call) RunAndReturn(run func(id string) (bool, error)) *resourceStoreInterfaceMock_IsResourceServerExist_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateAction(id string, resourceServerID string, resourceID *string, action Action) error {
	ret := _mock.Called(id, resourceServerID, resourceID, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string, Action) error); ok {
		r0 = returnFunc(id, resourceServerID, resourceID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAction'
type resourceStoreInterfaceMock_UpdateAction_Call struct {
	*mock.Call
}

// UpdateAction is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
//   - resourceID *string
//   - action Action
func (_e *resourceStoreInterfaceMock_Expecter) UpdateAction(id interface{}, resourceServerID interface{}, resourceID interface{}, action interface{}) *resourceStoreInterfaceMock_UpdateAction_Call {
	return &resourceStoreInterfaceMock_UpdateAction_Call{Call: _e.mock.On("UpdateAction", id, resourceServerID, resourceID, action)}
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) Run(run func(id string, resourceServerID string, resourceID *string, action Action)) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 Action
		if args[3] != nil {
			arg3 = args[3].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) Return(err error) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) RunAndReturn(run func(id string, resourceServerID string, resourceID *string, action Action) error) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateResource(id string, resourceServerID string, res Resource) error {
	ret := _mock.Called(id, resourceServerID, res)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, Resource) error); ok {
		r0 = returnFunc(id, resourceServerID, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type resourceStoreInterfaceMock_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - id string
//   - resourceServerID string
//   - res Resource
func (_e *resourceStoreInterfaceMock_Expecter) UpdateResource(id interface{}, resourceServerID interface{}, res interface{}) *resourceStoreInterfaceMock_UpdateResource_Call {
	return &resourceStoreInterfaceMock_UpdateResource_Call{Call: _e.mock.On("UpdateResource", id, resourceServerID, res)}
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) Run(run func(id string, resourceServerID string, res Resource)) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Resource
		if args[2] != nil {
			arg2 = args[2].(Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) Return(err error) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) RunAndReturn(run func(id string, resourceServerID string, res Resource) error) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateResourceServer(id string, rs ResourceServer) error {
	ret := _mock.Called(id, rs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ResourceServer) error); ok {
		r0 = returnFunc(id, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceServer'
type resourceStoreInterfaceMock_UpdateResourceServer_Call struct {
	*mock.Call
}

// UpdateResourceServer is a helper method to define mock.On call
//   - id string
//   - rs ResourceServer
func (_e *resourceStoreInterfaceMock_Expecter) UpdateResourceServer(id interface{}, rs interface{}) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	return &resourceStoreInterfaceMock_UpdateResourceServer_Call{Call: _e.mock.On("UpdateResourceServer", id, rs)}
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) Run(run func(id string, rs ResourceServer)) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 ResourceServer
		if args[1] != nil {
			arg1 = args[1].(ResourceServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) RunAndReturn(run func(id string, rs ResourceServer) error) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}
