// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userinfo

import (
	"context"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewUserInfoServiceInterfaceMock creates a new instance of UserInfoServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInfoServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInfoServiceInterfaceMock {
	mock := &UserInfoServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserInfoServiceInterfaceMock is an autogenerated mock type for the UserInfoServiceInterface type
type UserInfoServiceInterfaceMock struct {
	mock.Mock
}

type UserInfoServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInfoServiceInterfaceMock) EXPECT() *UserInfoServiceInterfaceMock_Expecter {
	return &UserInfoServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type UserInfoServiceInterfaceMock
func (_mock *UserInfoServiceInterfaceMock) GetUserInfo(ctx context.Context, accessToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserInfoServiceInterfaceMock_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type UserInfoServiceInterfaceMock_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *UserInfoServiceInterfaceMock_Expecter) GetUserInfo(ctx interface{}, accessToken interface{}) *UserInfoServiceInterfaceMock_GetUserInfo_Call {
	return &UserInfoServiceInterfaceMock_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, accessToken)}
}

func (_c *UserInfoServiceInterfaceMock_GetUserInfo_Call) Run(run func(ctx context.Context, accessToken string)) *UserInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserInfoServiceInterfaceMock_GetUserInfo_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *UserInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *UserInfoServiceInterfaceMock_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (map[string]interface{}, *serviceerror.ServiceError)) *UserInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
