// Code generated by mockery v2.53.4. DO NOT EDIT.

package validator

import (
	validator "github.com/asgardeo/thunder/internal/oauth/scope/validator"
	mock "github.com/stretchr/testify/mock"
)

// MockScopeValidatorInterface is an autogenerated mock type for the ScopeValidatorInterface type
type MockScopeValidatorInterface struct {
	mock.Mock
}

type MockScopeValidatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScopeValidatorInterface) EXPECT() *MockScopeValidatorInterface_Expecter {
	return &MockScopeValidatorInterface_Expecter{mock: &_m.Mock}
}

// ValidateScopes provides a mock function with given fields: requestedScopes, clientID
func (_m *MockScopeValidatorInterface) ValidateScopes(requestedScopes string, clientID string) (string, *validator.ScopeError) {
	ret := _m.Called(requestedScopes, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateScopes")
	}

	var r0 string
	var r1 *validator.ScopeError
	if rf, ok := ret.Get(0).(func(string, string) (string, *validator.ScopeError)); ok {
		return rf(requestedScopes, clientID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(requestedScopes, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) *validator.ScopeError); ok {
		r1 = rf(requestedScopes, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*validator.ScopeError)
		}
	}

	return r0, r1
}

// MockScopeValidatorInterface_ValidateScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateScopes'
type MockScopeValidatorInterface_ValidateScopes_Call struct {
	*mock.Call
}

// ValidateScopes is a helper method to define mock.On call
//   - requestedScopes string
//   - clientID string
func (_e *MockScopeValidatorInterface_Expecter) ValidateScopes(requestedScopes interface{}, clientID interface{}) *MockScopeValidatorInterface_ValidateScopes_Call {
	return &MockScopeValidatorInterface_ValidateScopes_Call{Call: _e.mock.On("ValidateScopes", requestedScopes, clientID)}
}

func (_c *MockScopeValidatorInterface_ValidateScopes_Call) Run(run func(requestedScopes string, clientID string)) *MockScopeValidatorInterface_ValidateScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockScopeValidatorInterface_ValidateScopes_Call) Return(_a0 string, _a1 *validator.ScopeError) *MockScopeValidatorInterface_ValidateScopes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScopeValidatorInterface_ValidateScopes_Call) RunAndReturn(run func(string, string) (string, *validator.ScopeError)) *MockScopeValidatorInterface_ValidateScopes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScopeValidatorInterface creates a new instance of MockScopeValidatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScopeValidatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScopeValidatorInterface {
	mock := &MockScopeValidatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
