// Code generated by mockery v2.53.4. DO NOT EDIT.

package granthandlersmock

import (
	applicationmodel "github.com/asgardeo/thunder/internal/application/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/asgardeo/thunder/internal/oauth/oauth2/model"
)

// MockGrantHandler is an autogenerated mock type for the GrantHandler type
type MockGrantHandler struct {
	mock.Mock
}

type MockGrantHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrantHandler) EXPECT() *MockGrantHandler_Expecter {
	return &MockGrantHandler_Expecter{mock: &_m.Mock}
}

// HandleGrant provides a mock function with given fields: tokenRequest, oauthApp, ctx
func (_m *MockGrantHandler) HandleGrant(tokenRequest *model.TokenRequest, oauthApp *applicationmodel.OAuthAppConfigProcessed, ctx *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse) {
	ret := _m.Called(tokenRequest, oauthApp, ctx)

	if len(ret) == 0 {
		panic("no return value specified for HandleGrant")
	}

	var r0 *model.TokenResponseDTO
	var r1 *model.ErrorResponse
	if rf, ok := ret.Get(0).(func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed, *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse)); ok {
		return rf(tokenRequest, oauthApp, ctx)
	}
	if rf, ok := ret.Get(0).(func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed, *model.TokenContext) *model.TokenResponseDTO); ok {
		r0 = rf(tokenRequest, oauthApp, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed, *model.TokenContext) *model.ErrorResponse); ok {
		r1 = rf(tokenRequest, oauthApp, ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorResponse)
		}
	}

	return r0, r1
}

// MockGrantHandler_HandleGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGrant'
type MockGrantHandler_HandleGrant_Call struct {
	*mock.Call
}

// HandleGrant is a helper method to define mock.On call
//   - tokenRequest *model.TokenRequest
//   - oauthApp *applicationmodel.OAuthAppConfigProcessed
//   - ctx *model.TokenContext
func (_e *MockGrantHandler_Expecter) HandleGrant(tokenRequest interface{}, oauthApp interface{}, ctx interface{}) *MockGrantHandler_HandleGrant_Call {
	return &MockGrantHandler_HandleGrant_Call{Call: _e.mock.On("HandleGrant", tokenRequest, oauthApp, ctx)}
}

func (_c *MockGrantHandler_HandleGrant_Call) Run(run func(tokenRequest *model.TokenRequest, oauthApp *applicationmodel.OAuthAppConfigProcessed, ctx *model.TokenContext)) *MockGrantHandler_HandleGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TokenRequest), args[1].(*applicationmodel.OAuthAppConfigProcessed), args[2].(*model.TokenContext))
	})
	return _c
}

func (_c *MockGrantHandler_HandleGrant_Call) Return(_a0 *model.TokenResponseDTO, _a1 *model.ErrorResponse) *MockGrantHandler_HandleGrant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGrantHandler_HandleGrant_Call) RunAndReturn(run func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed, *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse)) *MockGrantHandler_HandleGrant_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateGrant provides a mock function with given fields: tokenRequest, oauthApp
func (_m *MockGrantHandler) ValidateGrant(tokenRequest *model.TokenRequest, oauthApp *applicationmodel.OAuthAppConfigProcessed) *model.ErrorResponse {
	ret := _m.Called(tokenRequest, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateGrant")
	}

	var r0 *model.ErrorResponse
	if rf, ok := ret.Get(0).(func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed) *model.ErrorResponse); ok {
		r0 = rf(tokenRequest, oauthApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorResponse)
		}
	}

	return r0
}

// MockGrantHandler_ValidateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateGrant'
type MockGrantHandler_ValidateGrant_Call struct {
	*mock.Call
}

// ValidateGrant is a helper method to define mock.On call
//   - tokenRequest *model.TokenRequest
//   - oauthApp *applicationmodel.OAuthAppConfigProcessed
func (_e *MockGrantHandler_Expecter) ValidateGrant(tokenRequest interface{}, oauthApp interface{}) *MockGrantHandler_ValidateGrant_Call {
	return &MockGrantHandler_ValidateGrant_Call{Call: _e.mock.On("ValidateGrant", tokenRequest, oauthApp)}
}

func (_c *MockGrantHandler_ValidateGrant_Call) Run(run func(tokenRequest *model.TokenRequest, oauthApp *applicationmodel.OAuthAppConfigProcessed)) *MockGrantHandler_ValidateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TokenRequest), args[1].(*applicationmodel.OAuthAppConfigProcessed))
	})
	return _c
}

func (_c *MockGrantHandler_ValidateGrant_Call) Return(_a0 *model.ErrorResponse) *MockGrantHandler_ValidateGrant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGrantHandler_ValidateGrant_Call) RunAndReturn(run func(*model.TokenRequest, *applicationmodel.OAuthAppConfigProcessed) *model.ErrorResponse) *MockGrantHandler_ValidateGrant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrantHandler creates a new instance of MockGrantHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrantHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrantHandler {
	mock := &MockGrantHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
