// Code generated by mockery v2.53.4. DO NOT EDIT.

package store

import (
	model "github.com/asgardeo/thunder/internal/oauth/session/model"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionDataStoreInterface is an autogenerated mock type for the SessionDataStoreInterface type
type MockSessionDataStoreInterface struct {
	mock.Mock
}

type MockSessionDataStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionDataStoreInterface) EXPECT() *MockSessionDataStoreInterface_Expecter {
	return &MockSessionDataStoreInterface_Expecter{mock: &_m.Mock}
}

// AddSession provides a mock function with given fields: key, value
func (_m *MockSessionDataStoreInterface) AddSession(key string, value model.SessionData) {
	_m.Called(key, value)
}

// MockSessionDataStoreInterface_AddSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSession'
type MockSessionDataStoreInterface_AddSession_Call struct {
	*mock.Call
}

// AddSession is a helper method to define mock.On call
//   - key string
//   - value model.SessionData
func (_e *MockSessionDataStoreInterface_Expecter) AddSession(key interface{}, value interface{}) *MockSessionDataStoreInterface_AddSession_Call {
	return &MockSessionDataStoreInterface_AddSession_Call{Call: _e.mock.On("AddSession", key, value)}
}

func (_c *MockSessionDataStoreInterface_AddSession_Call) Run(run func(key string, value model.SessionData)) *MockSessionDataStoreInterface_AddSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.SessionData))
	})
	return _c
}

func (_c *MockSessionDataStoreInterface_AddSession_Call) Return() *MockSessionDataStoreInterface_AddSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionDataStoreInterface_AddSession_Call) RunAndReturn(run func(string, model.SessionData)) *MockSessionDataStoreInterface_AddSession_Call {
	_c.Run(run)
	return _c
}

// ClearSession provides a mock function with given fields: key
func (_m *MockSessionDataStoreInterface) ClearSession(key string) {
	_m.Called(key)
}

// MockSessionDataStoreInterface_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockSessionDataStoreInterface_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - key string
func (_e *MockSessionDataStoreInterface_Expecter) ClearSession(key interface{}) *MockSessionDataStoreInterface_ClearSession_Call {
	return &MockSessionDataStoreInterface_ClearSession_Call{Call: _e.mock.On("ClearSession", key)}
}

func (_c *MockSessionDataStoreInterface_ClearSession_Call) Run(run func(key string)) *MockSessionDataStoreInterface_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionDataStoreInterface_ClearSession_Call) Return() *MockSessionDataStoreInterface_ClearSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionDataStoreInterface_ClearSession_Call) RunAndReturn(run func(string)) *MockSessionDataStoreInterface_ClearSession_Call {
	_c.Run(run)
	return _c
}

// ClearSessionStore provides a mock function with no fields
func (_m *MockSessionDataStoreInterface) ClearSessionStore() {
	_m.Called()
}

// MockSessionDataStoreInterface_ClearSessionStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSessionStore'
type MockSessionDataStoreInterface_ClearSessionStore_Call struct {
	*mock.Call
}

// ClearSessionStore is a helper method to define mock.On call
func (_e *MockSessionDataStoreInterface_Expecter) ClearSessionStore() *MockSessionDataStoreInterface_ClearSessionStore_Call {
	return &MockSessionDataStoreInterface_ClearSessionStore_Call{Call: _e.mock.On("ClearSessionStore")}
}

func (_c *MockSessionDataStoreInterface_ClearSessionStore_Call) Run(run func()) *MockSessionDataStoreInterface_ClearSessionStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionDataStoreInterface_ClearSessionStore_Call) Return() *MockSessionDataStoreInterface_ClearSessionStore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionDataStoreInterface_ClearSessionStore_Call) RunAndReturn(run func()) *MockSessionDataStoreInterface_ClearSessionStore_Call {
	_c.Run(run)
	return _c
}

// GetSession provides a mock function with given fields: key
func (_m *MockSessionDataStoreInterface) GetSession(key string) (bool, model.SessionData) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 bool
	var r1 model.SessionData
	if rf, ok := ret.Get(0).(func(string) (bool, model.SessionData)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) model.SessionData); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(model.SessionData)
	}

	return r0, r1
}

// MockSessionDataStoreInterface_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionDataStoreInterface_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - key string
func (_e *MockSessionDataStoreInterface_Expecter) GetSession(key interface{}) *MockSessionDataStoreInterface_GetSession_Call {
	return &MockSessionDataStoreInterface_GetSession_Call{Call: _e.mock.On("GetSession", key)}
}

func (_c *MockSessionDataStoreInterface_GetSession_Call) Run(run func(key string)) *MockSessionDataStoreInterface_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionDataStoreInterface_GetSession_Call) Return(_a0 bool, _a1 model.SessionData) *MockSessionDataStoreInterface_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionDataStoreInterface_GetSession_Call) RunAndReturn(run func(string) (bool, model.SessionData)) *MockSessionDataStoreInterface_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionDataStoreInterface creates a new instance of MockSessionDataStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionDataStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionDataStoreInterface {
	mock := &MockSessionDataStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
