// Code generated by mockery v2.53.4. DO NOT EDIT.

package clientmock

import (
	model "github.com/asgardeo/thunder/internal/system/database/model"
	mock "github.com/stretchr/testify/mock"
)

// MockDBClientInterface is an autogenerated mock type for the DBClientInterface type
type MockDBClientInterface struct {
	mock.Mock
}

type MockDBClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBClientInterface) EXPECT() *MockDBClientInterface_Expecter {
	return &MockDBClientInterface_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with no fields
func (_m *MockDBClientInterface) BeginTx() (model.TxInterface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 model.TxInterface
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.TxInterface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.TxInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.TxInterface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClientInterface_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDBClientInterface_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
func (_e *MockDBClientInterface_Expecter) BeginTx() *MockDBClientInterface_BeginTx_Call {
	return &MockDBClientInterface_BeginTx_Call{Call: _e.mock.On("BeginTx")}
}

func (_c *MockDBClientInterface_BeginTx_Call) Run(run func()) *MockDBClientInterface_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBClientInterface_BeginTx_Call) Return(_a0 model.TxInterface, _a1 error) *MockDBClientInterface_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClientInterface_BeginTx_Call) RunAndReturn(run func() (model.TxInterface, error)) *MockDBClientInterface_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockDBClientInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBClientInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDBClientInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDBClientInterface_Expecter) Close() *MockDBClientInterface_Close_Call {
	return &MockDBClientInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDBClientInterface_Close_Call) Run(run func()) *MockDBClientInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBClientInterface_Close_Call) Return(_a0 error) *MockDBClientInterface_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBClientInterface_Close_Call) RunAndReturn(run func() error) *MockDBClientInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: query, args
func (_m *MockDBClientInterface) Execute(query model.DBQuery, args ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) (int64, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) int64); ok {
		r0 = rf(query, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClientInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDBClientInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *MockDBClientInterface_Expecter) Execute(query interface{}, args ...interface{}) *MockDBClientInterface_Execute_Call {
	return &MockDBClientInterface_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDBClientInterface_Execute_Call) Run(run func(query model.DBQuery, args ...interface{})) *MockDBClientInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *MockDBClientInterface_Execute_Call) Return(_a0 int64, _a1 error) *MockDBClientInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClientInterface_Execute_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) (int64, error)) *MockDBClientInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *MockDBClientInterface) Query(query model.DBQuery, args ...interface{}) ([]map[string]interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) ([]map[string]interface{}, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(model.DBQuery, ...interface{}) []map[string]interface{}); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(model.DBQuery, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBClientInterface_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDBClientInterface_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query model.DBQuery
//   - args ...interface{}
func (_e *MockDBClientInterface_Expecter) Query(query interface{}, args ...interface{}) *MockDBClientInterface_Query_Call {
	return &MockDBClientInterface_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDBClientInterface_Query_Call) Run(run func(query model.DBQuery, args ...interface{})) *MockDBClientInterface_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(model.DBQuery), variadicArgs...)
	})
	return _c
}

func (_c *MockDBClientInterface_Query_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockDBClientInterface_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBClientInterface_Query_Call) RunAndReturn(run func(model.DBQuery, ...interface{}) ([]map[string]interface{}, error)) *MockDBClientInterface_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBClientInterface creates a new instance of MockDBClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBClientInterface {
	mock := &MockDBClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
