// Code generated by mockery v2.53.4. DO NOT EDIT.

package authz

import (
	applicationmodel "github.com/asgardeo/thunder/internal/application/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/asgardeo/thunder/internal/oauth/oauth2/authz/model"
)

// MockAuthorizationValidatorInterface is an autogenerated mock type for the AuthorizationValidatorInterface type
type MockAuthorizationValidatorInterface struct {
	mock.Mock
}

type MockAuthorizationValidatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationValidatorInterface) EXPECT() *MockAuthorizationValidatorInterface_Expecter {
	return &MockAuthorizationValidatorInterface_Expecter{mock: &_m.Mock}
}

// validateInitialAuthorizationRequest provides a mock function with given fields: msg, oauthApp
func (_m *MockAuthorizationValidatorInterface) validateInitialAuthorizationRequest(msg *model.OAuthMessage, oauthApp *applicationmodel.OAuthAppConfigProcessed) (bool, string, string) {
	ret := _m.Called(msg, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for validateInitialAuthorizationRequest")
	}

	var r0 bool
	var r1 string
	var r2 string
	if rf, ok := ret.Get(0).(func(*model.OAuthMessage, *applicationmodel.OAuthAppConfigProcessed) (bool, string, string)); ok {
		return rf(msg, oauthApp)
	}
	if rf, ok := ret.Get(0).(func(*model.OAuthMessage, *applicationmodel.OAuthAppConfigProcessed) bool); ok {
		r0 = rf(msg, oauthApp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*model.OAuthMessage, *applicationmodel.OAuthAppConfigProcessed) string); ok {
		r1 = rf(msg, oauthApp)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*model.OAuthMessage, *applicationmodel.OAuthAppConfigProcessed) string); ok {
		r2 = rf(msg, oauthApp)
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

// MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validateInitialAuthorizationRequest'
type MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call struct {
	*mock.Call
}

// validateInitialAuthorizationRequest is a helper method to define mock.On call
//   - msg *model.OAuthMessage
//   - oauthApp *applicationmodel.OAuthAppConfigProcessed
func (_e *MockAuthorizationValidatorInterface_Expecter) validateInitialAuthorizationRequest(msg interface{}, oauthApp interface{}) *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call {
	return &MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call{Call: _e.mock.On("validateInitialAuthorizationRequest", msg, oauthApp)}
}

func (_c *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call) Run(run func(msg *model.OAuthMessage, oauthApp *applicationmodel.OAuthAppConfigProcessed)) *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.OAuthMessage), args[1].(*applicationmodel.OAuthAppConfigProcessed))
	})
	return _c
}

func (_c *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call) Return(_a0 bool, _a1 string, _a2 string) *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call) RunAndReturn(run func(*model.OAuthMessage, *applicationmodel.OAuthAppConfigProcessed) (bool, string, string)) *MockAuthorizationValidatorInterface_validateInitialAuthorizationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizationValidatorInterface creates a new instance of MockAuthorizationValidatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizationValidatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizationValidatorInterface {
	mock := &MockAuthorizationValidatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
