// Code generated by mockery v2.53.4. DO NOT EDIT.

package authz

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorizeHandlerInterface is an autogenerated mock type for the AuthorizeHandlerInterface type
type MockAuthorizeHandlerInterface struct {
	mock.Mock
}

type MockAuthorizeHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizeHandlerInterface) EXPECT() *MockAuthorizeHandlerInterface_Expecter {
	return &MockAuthorizeHandlerInterface_Expecter{mock: &_m.Mock}
}

// HandleAuthorizeGetRequest provides a mock function with given fields: w, r
func (_m *MockAuthorizeHandlerInterface) HandleAuthorizeGetRequest(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthorizeGetRequest'
type MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call struct {
	*mock.Call
}

// HandleAuthorizeGetRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockAuthorizeHandlerInterface_Expecter) HandleAuthorizeGetRequest(w interface{}, r interface{}) *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call {
	return &MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call{Call: _e.mock.On("HandleAuthorizeGetRequest", w, r)}
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call) Return() *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockAuthorizeHandlerInterface_HandleAuthorizeGetRequest_Call {
	_c.Run(run)
	return _c
}

// HandleAuthorizePostRequest provides a mock function with given fields: w, r
func (_m *MockAuthorizeHandlerInterface) HandleAuthorizePostRequest(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthorizePostRequest'
type MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call struct {
	*mock.Call
}

// HandleAuthorizePostRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockAuthorizeHandlerInterface_Expecter) HandleAuthorizePostRequest(w interface{}, r interface{}) *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call {
	return &MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call{Call: _e.mock.On("HandleAuthorizePostRequest", w, r)}
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call) Return() *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockAuthorizeHandlerInterface_HandleAuthorizePostRequest_Call {
	_c.Run(run)
	return _c
}

// NewMockAuthorizeHandlerInterface creates a new instance of MockAuthorizeHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizeHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizeHandlerInterface {
	mock := &MockAuthorizeHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
