// Code generated by mockery v2.53.4. DO NOT EDIT.

package service

import (
	model "github.com/asgardeo/thunder/internal/system/healthcheck/model"
	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckServiceInterface is an autogenerated mock type for the HealthCheckServiceInterface type
type MockHealthCheckServiceInterface struct {
	mock.Mock
}

type MockHealthCheckServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckServiceInterface) EXPECT() *MockHealthCheckServiceInterface_Expecter {
	return &MockHealthCheckServiceInterface_Expecter{mock: &_m.Mock}
}

// CheckReadiness provides a mock function with no fields
func (_m *MockHealthCheckServiceInterface) CheckReadiness() model.ServerStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckReadiness")
	}

	var r0 model.ServerStatus
	if rf, ok := ret.Get(0).(func() model.ServerStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ServerStatus)
	}

	return r0
}

// MockHealthCheckServiceInterface_CheckReadiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckReadiness'
type MockHealthCheckServiceInterface_CheckReadiness_Call struct {
	*mock.Call
}

// CheckReadiness is a helper method to define mock.On call
func (_e *MockHealthCheckServiceInterface_Expecter) CheckReadiness() *MockHealthCheckServiceInterface_CheckReadiness_Call {
	return &MockHealthCheckServiceInterface_CheckReadiness_Call{Call: _e.mock.On("CheckReadiness")}
}

func (_c *MockHealthCheckServiceInterface_CheckReadiness_Call) Run(run func()) *MockHealthCheckServiceInterface_CheckReadiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckServiceInterface_CheckReadiness_Call) Return(_a0 model.ServerStatus) *MockHealthCheckServiceInterface_CheckReadiness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckServiceInterface_CheckReadiness_Call) RunAndReturn(run func() model.ServerStatus) *MockHealthCheckServiceInterface_CheckReadiness_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckServiceInterface creates a new instance of MockHealthCheckServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckServiceInterface {
	mock := &MockHealthCheckServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
