-- Table to store User Schemas
CREATE TABLE USER_SCHEMAS (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCHEMA_ID   VARCHAR(36) UNIQUE NOT NULL,
    NAME        VARCHAR(100) UNIQUE NOT NULL,
    OU_ID       VARCHAR(36) NOT NULL,
    ALLOW_SELF_REGISTRATION BOOLEAN DEFAULT FALSE NOT NULL,
    SCHEMA_DEF  JSONB NOT NULL,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store Roles
CREATE TABLE "ROLE" (
    ID                  INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID             VARCHAR(36) UNIQUE NOT NULL,
    OU_ID               VARCHAR(36) NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    DESCRIPTION         VARCHAR(255),
    CREATED_AT          TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT          TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_role_ou_name UNIQUE (OU_ID, NAME)
);

-- Table to store Role permissions
CREATE TABLE ROLE_PERMISSION (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID         VARCHAR(36) NOT NULL,
    PERMISSION      VARCHAR(100) NOT NULL,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (ROLE_ID) REFERENCES "ROLE" (ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_permission UNIQUE (ROLE_ID, PERMISSION)
);

-- Table to store Role assignments (to users and groups)
CREATE TABLE ROLE_ASSIGNMENT (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID         VARCHAR(36) NOT NULL,
    ASSIGNEE_TYPE   VARCHAR(5)  NOT NULL CHECK (ASSIGNEE_TYPE IN ('user', 'group')),
    ASSIGNEE_ID     VARCHAR(36) NOT NULL,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (ROLE_ID) REFERENCES "ROLE" (ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_assignment UNIQUE (ROLE_ID, ASSIGNEE_TYPE, ASSIGNEE_ID)
);

-- Indexes for authorization queries

-- Index for finding all roles assigned to a specific assignee
CREATE INDEX idx_role_assignment_assignee 
ON ROLE_ASSIGNMENT (ASSIGNEE_ID, ASSIGNEE_TYPE);

-- Index for finding all permissions for a specific role
CREATE INDEX idx_role_permission_role 
ON ROLE_PERMISSION (ROLE_ID);

-- Table to store branding configurations.
CREATE TABLE BRANDING (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BRANDING_ID VARCHAR(36) UNIQUE NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    PREFERENCES JSONB NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store basic service provider (app) details.
CREATE TABLE SP_APP (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID VARCHAR(36) UNIQUE NOT NULL,
    APP_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AUTH_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    REGISTRATION_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    IS_REGISTRATION_FLOW_ENABLED CHAR(1) DEFAULT '1',
    BRANDING_ID VARCHAR(36),
    APP_JSON JSONB,
    FOREIGN KEY (BRANDING_ID) REFERENCES BRANDING(BRANDING_ID) ON DELETE RESTRICT
);

-- Index for efficient lookups of applications by branding.
CREATE INDEX idx_sp_app_branding_id ON SP_APP(BRANDING_ID);

-- Table to store OAuth configurations for SP apps.
CREATE TABLE IDN_OAUTH_CONSUMER_APPS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    CONSUMER_SECRET VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL REFERENCES SP_APP(APP_ID) ON DELETE CASCADE,
    OAUTH_CONFIG_JSON JSONB
);

-- Table to store inbound auth configs (e.g., OAuth, SAML) for SP apps.
CREATE TABLE SP_INBOUND_AUTH (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INBOUND_AUTH_KEY VARCHAR(255) NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL REFERENCES SP_APP(APP_ID) ON DELETE CASCADE
);

-- Table to store identity providers.
CREATE TABLE IDP (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDP_ID VARCHAR(36) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store notification senders.
CREATE TABLE NOTIFICATION_SENDER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SENDER_ID VARCHAR(36) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROVIDER VARCHAR(20) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store certificates associated with various entities.
CREATE TABLE CERTIFICATE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CERT_ID VARCHAR(36) UNIQUE NOT NULL,
    REF_TYPE VARCHAR(20) NOT NULL,
    REF_ID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    VALUE TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (REF_TYPE, REF_ID)
);

-- Table to store resource servers.
CREATE TABLE RESOURCE_SERVER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESOURCE_SERVER_ID VARCHAR(36) NOT NULL UNIQUE,
    OU_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    IDENTIFIER VARCHAR(100),
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Unique constraint: Resource server name must be unique within an OU
CREATE UNIQUE INDEX uq_resource_server_ou_name
    ON RESOURCE_SERVER(OU_ID, NAME);

-- Unique constraint: Resource server identifier must be globally unique (when not null)
CREATE UNIQUE INDEX uq_resource_server_identifier
    ON RESOURCE_SERVER(IDENTIFIER)
    WHERE IDENTIFIER IS NOT NULL;

-- Table to store resources within resource servers.
CREATE TABLE RESOURCE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESOURCE_ID VARCHAR(36) NOT NULL UNIQUE,
    RESOURCE_SERVER_ID INT NOT NULL,
    PARENT_RESOURCE_ID INT,
    NAME VARCHAR(100) NOT NULL,
    HANDLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),

    FOREIGN KEY (RESOURCE_SERVER_ID)
        REFERENCES RESOURCE_SERVER(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (PARENT_RESOURCE_ID)
        REFERENCES RESOURCE(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Unique constraint: Resource handle must be unique under the same parent
CREATE UNIQUE INDEX uq_resource_handle_with_parent
    ON RESOURCE(RESOURCE_SERVER_ID, PARENT_RESOURCE_ID, HANDLE)
    WHERE PARENT_RESOURCE_ID IS NOT NULL;

-- Unique constraint: Root-level resource handles must be unique per resource server
CREATE UNIQUE INDEX uq_resource_handle_null_parent
    ON RESOURCE(RESOURCE_SERVER_ID, HANDLE)
    WHERE PARENT_RESOURCE_ID IS NULL;

-- Table to store actions at resource server or resource level.
CREATE TABLE ACTION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACTION_ID VARCHAR(36) NOT NULL UNIQUE,
    RESOURCE_SERVER_ID INT NOT NULL,
    RESOURCE_ID INT,
    NAME VARCHAR(100) NOT NULL,
    HANDLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),

    FOREIGN KEY (RESOURCE_SERVER_ID)
        REFERENCES RESOURCE_SERVER(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (RESOURCE_ID)
        REFERENCES RESOURCE(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Unique constraint: Server-level action handles must be unique per resource server
CREATE UNIQUE INDEX uq_action_server_handle
    ON ACTION(RESOURCE_SERVER_ID, HANDLE)
    WHERE RESOURCE_ID IS NULL;

-- Unique constraint: Resource-level action handles must be unique per resource
CREATE UNIQUE INDEX uq_action_resource_handle
    ON ACTION(RESOURCE_ID, HANDLE)
    WHERE RESOURCE_ID IS NOT NULL;
