notificationSenders:
  - id: "email_sender_1"
    name: "Default Email Sender"
    description: "Sends notification emails using SMTP"
    type: "EMAIL"
    provider: "SMTP"
    properties:
      - key: "smtp_host"
        value: "smtp.example.com"
      - key: "smtp_port"
        value: "587"
      - key: "username"
        value: "noreply@example.com"
      - key: "from_name"
        value: "Thunder Notifications"

  - id: "sms_sender_1"
    name: "Primary SMS Sender"
    description: "Sends SMS notifications via Twilio"
    type: "SMS"
    provider: "TWILIO"
    properties:
      - key: "account_sid"
        value: "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      - key: "auth_token"
        value: "your_auth_token"
      - key: "from_number"
        value: "+1234567890"

  - id: "push_sender_1"
    name: "Push Notification Sender"
    description: "Sends push notifications using Firebase"
    type: "PUSH"
    provider: "FIREBASE"
    properties:
      - key: "firebase_project_id"
        value: "my-firebase-project"
      - key: "service_account_json"
        value: "/path/to/serviceAccountKey.json"

identityProviders:
  - id: "google_oauth"
    name: "Google OAuth"
    description: "Authenticate users via Google OAuth 2.0"
    type: "OAUT"
    properties:
      - key: "client_id"
        value: "your-google-client-id.apps.googleusercontent.com"
      - key: "client_secret"
        value: "your-google-client-secret"
      - key: "redirect_uri"
        value: "https://yourapp.example.com/auth/callback/google"
      - key: "scopes"
        value: "openid,email,profile"

  - id: "ldap_corp"
    name: "Corporate LDAP"
    description: "Authenticate users against corporate LDAP directory"
    type: "LDAP"
    properties:
      - key: "ldap_url"
        value: "ldaps://ldap.corp.example.com:636"
      - key: "bind_dn"
        value: "cn=admin,dc=corp,dc=example,dc=com"
      - key: "bind_password"
        value: "your-ldap-password"
      - key: "user_base_dn"
        value: "ou=users,dc=corp,dc=example,dc=com"
      - key: "user_filter"
        value: "(objectClass=person)"

  - id: "saml_enterprise"
    name: "Enterprise SAML"
    description: "Authenticate users via SAML 2.0"
    type: "SAML"
    properties:
      - key: "idp_entity_id"
        value: "https://idp.example.com/entity"
      - key: "sso_url"
        value: "https://idp.example.com/sso"
      - key: "x509_cert"
        value: "/path/to/idp_cert.pem"
      - key: "acs_url"
        value: "https://yourapp.example.com/auth/callback/saml"