// Code generated by mockery v2.53.4. DO NOT EDIT.

package token

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenHandlerInterface is an autogenerated mock type for the TokenHandlerInterface type
type MockTokenHandlerInterface struct {
	mock.Mock
}

type MockTokenHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenHandlerInterface) EXPECT() *MockTokenHandlerInterface_Expecter {
	return &MockTokenHandlerInterface_Expecter{mock: &_m.Mock}
}

// HandleTokenRequest provides a mock function with given fields: w, r
func (_m *MockTokenHandlerInterface) HandleTokenRequest(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockTokenHandlerInterface_HandleTokenRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTokenRequest'
type MockTokenHandlerInterface_HandleTokenRequest_Call struct {
	*mock.Call
}

// HandleTokenRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockTokenHandlerInterface_Expecter) HandleTokenRequest(w interface{}, r interface{}) *MockTokenHandlerInterface_HandleTokenRequest_Call {
	return &MockTokenHandlerInterface_HandleTokenRequest_Call{Call: _e.mock.On("HandleTokenRequest", w, r)}
}

func (_c *MockTokenHandlerInterface_HandleTokenRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockTokenHandlerInterface_HandleTokenRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockTokenHandlerInterface_HandleTokenRequest_Call) Return() *MockTokenHandlerInterface_HandleTokenRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTokenHandlerInterface_HandleTokenRequest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockTokenHandlerInterface_HandleTokenRequest_Call {
	_c.Run(run)
	return _c
}

// NewMockTokenHandlerInterface creates a new instance of MockTokenHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenHandlerInterface {
	mock := &MockTokenHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
