// Code generated by mockery v2.53.4. DO NOT EDIT.

package provider

import (
	client "github.com/asgardeo/thunder/internal/system/database/client"
	mock "github.com/stretchr/testify/mock"
)

// MockDBProviderInterface is an autogenerated mock type for the DBProviderInterface type
type MockDBProviderInterface struct {
	mock.Mock
}

type MockDBProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBProviderInterface) EXPECT() *MockDBProviderInterface_Expecter {
	return &MockDBProviderInterface_Expecter{mock: &_m.Mock}
}

// GetDBClient provides a mock function with given fields: dbName
func (_m *MockDBProviderInterface) GetDBClient(dbName string) (client.DBClientInterface, error) {
	ret := _m.Called(dbName)

	if len(ret) == 0 {
		panic("no return value specified for GetDBClient")
	}

	var r0 client.DBClientInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (client.DBClientInterface, error)); ok {
		return rf(dbName)
	}
	if rf, ok := ret.Get(0).(func(string) client.DBClientInterface); ok {
		r0 = rf(dbName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.DBClientInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dbName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBProviderInterface_GetDBClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDBClient'
type MockDBProviderInterface_GetDBClient_Call struct {
	*mock.Call
}

// GetDBClient is a helper method to define mock.On call
//   - dbName string
func (_e *MockDBProviderInterface_Expecter) GetDBClient(dbName interface{}) *MockDBProviderInterface_GetDBClient_Call {
	return &MockDBProviderInterface_GetDBClient_Call{Call: _e.mock.On("GetDBClient", dbName)}
}

func (_c *MockDBProviderInterface_GetDBClient_Call) Run(run func(dbName string)) *MockDBProviderInterface_GetDBClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDBProviderInterface_GetDBClient_Call) Return(_a0 client.DBClientInterface, _a1 error) *MockDBProviderInterface_GetDBClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBProviderInterface_GetDBClient_Call) RunAndReturn(run func(string) (client.DBClientInterface, error)) *MockDBProviderInterface_GetDBClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBProviderInterface creates a new instance of MockDBProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBProviderInterface {
	mock := &MockDBProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
