// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providermock

import (
	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewRedisClientInterfaceMock creates a new instance of RedisClientInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisClientInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisClientInterfaceMock {
	mock := &RedisClientInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisClientInterfaceMock is an autogenerated mock type for the RedisClientInterface type
type RedisClientInterfaceMock struct {
	mock.Mock
}

type RedisClientInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisClientInterfaceMock) EXPECT() *RedisClientInterfaceMock_Expecter {
	return &RedisClientInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetKeyPrefix provides a mock function for the type RedisClientInterfaceMock
func (_mock *RedisClientInterfaceMock) GetKeyPrefix() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeyPrefix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// RedisClientInterfaceMock_GetKeyPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyPrefix'
type RedisClientInterfaceMock_GetKeyPrefix_Call struct {
	*mock.Call
}

// GetKeyPrefix is a helper method to define mock.On call
func (_e *RedisClientInterfaceMock_Expecter) GetKeyPrefix() *RedisClientInterfaceMock_GetKeyPrefix_Call {
	return &RedisClientInterfaceMock_GetKeyPrefix_Call{Call: _e.mock.On("GetKeyPrefix")}
}

func (_c *RedisClientInterfaceMock_GetKeyPrefix_Call) Run(run func()) *RedisClientInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisClientInterfaceMock_GetKeyPrefix_Call) Return(s string) *RedisClientInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *RedisClientInterfaceMock_GetKeyPrefix_Call) RunAndReturn(run func() string) *RedisClientInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetRedisClient provides a mock function for the type RedisClientInterfaceMock
func (_mock *RedisClientInterfaceMock) GetRedisClient() *redis.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRedisClient")
	}

	var r0 *redis.Client
	if returnFunc, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}
	return r0
}

// RedisClientInterfaceMock_GetRedisClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRedisClient'
type RedisClientInterfaceMock_GetRedisClient_Call struct {
	*mock.Call
}

// GetRedisClient is a helper method to define mock.On call
func (_e *RedisClientInterfaceMock_Expecter) GetRedisClient() *RedisClientInterfaceMock_GetRedisClient_Call {
	return &RedisClientInterfaceMock_GetRedisClient_Call{Call: _e.mock.On("GetRedisClient")}
}

func (_c *RedisClientInterfaceMock_GetRedisClient_Call) Run(run func()) *RedisClientInterfaceMock_GetRedisClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisClientInterfaceMock_GetRedisClient_Call) Return(client *redis.Client) *RedisClientInterfaceMock_GetRedisClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *RedisClientInterfaceMock_GetRedisClient_Call) RunAndReturn(run func() *redis.Client) *RedisClientInterfaceMock_GetRedisClient_Call {
	_c.Call.Return(run)
	return _c
}
