// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providermock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewRedisRuntimeProviderCloserMock creates a new instance of RedisRuntimeProviderCloserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisRuntimeProviderCloserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisRuntimeProviderCloserMock {
	mock := &RedisRuntimeProviderCloserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisRuntimeProviderCloserMock is an autogenerated mock type for the RedisRuntimeProviderCloser type
type RedisRuntimeProviderCloserMock struct {
	mock.Mock
}

type RedisRuntimeProviderCloserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisRuntimeProviderCloserMock) EXPECT() *RedisRuntimeProviderCloserMock_Expecter {
	return &RedisRuntimeProviderCloserMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type RedisRuntimeProviderCloserMock
func (_mock *RedisRuntimeProviderCloserMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisRuntimeProviderCloserMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RedisRuntimeProviderCloserMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *RedisRuntimeProviderCloserMock_Expecter) Close() *RedisRuntimeProviderCloserMock_Close_Call {
	return &RedisRuntimeProviderCloserMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *RedisRuntimeProviderCloserMock_Close_Call) Run(run func()) *RedisRuntimeProviderCloserMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisRuntimeProviderCloserMock_Close_Call) Return(err error) *RedisRuntimeProviderCloserMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisRuntimeProviderCloserMock_Close_Call) RunAndReturn(run func() error) *RedisRuntimeProviderCloserMock_Close_Call {
	_c.Call.Return(run)
	return _c
}
