// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providermock

import (
	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewRedisRuntimeProviderInterfaceMock creates a new instance of RedisRuntimeProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisRuntimeProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisRuntimeProviderInterfaceMock {
	mock := &RedisRuntimeProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisRuntimeProviderInterfaceMock is an autogenerated mock type for the RedisRuntimeProviderInterface type
type RedisRuntimeProviderInterfaceMock struct {
	mock.Mock
}

type RedisRuntimeProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisRuntimeProviderInterfaceMock) EXPECT() *RedisRuntimeProviderInterfaceMock_Expecter {
	return &RedisRuntimeProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetKeyPrefix provides a mock function for the type RedisRuntimeProviderInterfaceMock
func (_mock *RedisRuntimeProviderInterfaceMock) GetKeyPrefix() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeyPrefix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyPrefix'
type RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call struct {
	*mock.Call
}

// GetKeyPrefix is a helper method to define mock.On call
func (_e *RedisRuntimeProviderInterfaceMock_Expecter) GetKeyPrefix() *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call {
	return &RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call{Call: _e.mock.On("GetKeyPrefix")}
}

func (_c *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call) Run(run func()) *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call) Return(s string) *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call) RunAndReturn(run func() string) *RedisRuntimeProviderInterfaceMock_GetKeyPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetRedisClient provides a mock function for the type RedisRuntimeProviderInterfaceMock
func (_mock *RedisRuntimeProviderInterfaceMock) GetRedisClient() *redis.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRedisClient")
	}

	var r0 *redis.Client
	if returnFunc, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}
	return r0
}

// RedisRuntimeProviderInterfaceMock_GetRedisClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRedisClient'
type RedisRuntimeProviderInterfaceMock_GetRedisClient_Call struct {
	*mock.Call
}

// GetRedisClient is a helper method to define mock.On call
func (_e *RedisRuntimeProviderInterfaceMock_Expecter) GetRedisClient() *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call {
	return &RedisRuntimeProviderInterfaceMock_GetRedisClient_Call{Call: _e.mock.On("GetRedisClient")}
}

func (_c *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call) Run(run func()) *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call) Return(client *redis.Client) *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call) RunAndReturn(run func() *redis.Client) *RedisRuntimeProviderInterfaceMock_GetRedisClient_Call {
	_c.Call.Return(run)
	return _c
}
