// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role

import (
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleServiceInterfaceMock creates a new instance of RoleServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleServiceInterfaceMock {
	mock := &RoleServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleServiceInterfaceMock is an autogenerated mock type for the RoleServiceInterface type
type RoleServiceInterfaceMock struct {
	mock.Mock
}

type RoleServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleServiceInterfaceMock) EXPECT() *RoleServiceInterfaceMock_Expecter {
	return &RoleServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) AddAssignments(roleID string, request AssignmentsRequest) *serviceerror.ServiceError {
	ret := _mock.Called(roleID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, AssignmentsRequest) *serviceerror.ServiceError); ok {
		r0 = returnFunc(roleID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_AddAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssignments'
type RoleServiceInterfaceMock_AddAssignments_Call struct {
	*mock.Call
}

// AddAssignments is a helper method to define mock.On call
//   - roleID string
//   - request AssignmentsRequest
func (_e *RoleServiceInterfaceMock_Expecter) AddAssignments(roleID interface{}, request interface{}) *RoleServiceInterfaceMock_AddAssignments_Call {
	return &RoleServiceInterfaceMock_AddAssignments_Call{Call: _e.mock.On("AddAssignments", roleID, request)}
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) Run(run func(roleID string, request AssignmentsRequest)) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 AssignmentsRequest
		if args[1] != nil {
			arg1 = args[1].(AssignmentsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_AddAssignments_Call) RunAndReturn(run func(roleID string, request AssignmentsRequest) *serviceerror.ServiceError) *RoleServiceInterfaceMock_AddAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) CreateRole(request CreateRoleRequest) (*Role, *serviceerror.ServiceError) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *Role
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(CreateRoleRequest) (*Role, *serviceerror.ServiceError)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(CreateRoleRequest) *Role); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(CreateRoleRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type RoleServiceInterfaceMock_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - request CreateRoleRequest
func (_e *RoleServiceInterfaceMock_Expecter) CreateRole(request interface{}) *RoleServiceInterfaceMock_CreateRole_Call {
	return &RoleServiceInterfaceMock_CreateRole_Call{Call: _e.mock.On("CreateRole", request)}
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) Run(run func(request CreateRoleRequest)) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CreateRoleRequest
		if args[0] != nil {
			arg0 = args[0].(CreateRoleRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) Return(role *Role, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Return(role, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_CreateRole_Call) RunAndReturn(run func(request CreateRoleRequest) (*Role, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) DeleteRole(roleID string) *serviceerror.ServiceError {
	ret := _mock.Called(roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type RoleServiceInterfaceMock_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - roleID string
func (_e *RoleServiceInterfaceMock_Expecter) DeleteRole(roleID interface{}) *RoleServiceInterfaceMock_DeleteRole_Call {
	return &RoleServiceInterfaceMock_DeleteRole_Call{Call: _e.mock.On("DeleteRole", roleID)}
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) Run(run func(roleID string)) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_DeleteRole_Call) RunAndReturn(run func(roleID string) *serviceerror.ServiceError) *RoleServiceInterfaceMock_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRole(roleID string) (*Role, *serviceerror.ServiceError) {
	ret := _mock.Called(roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *Role
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*Role, *serviceerror.ServiceError)); ok {
		return returnFunc(roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Role); ok {
		r0 = returnFunc(roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(roleID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type RoleServiceInterfaceMock_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - roleID string
func (_e *RoleServiceInterfaceMock_Expecter) GetRole(roleID interface{}) *RoleServiceInterfaceMock_GetRole_Call {
	return &RoleServiceInterfaceMock_GetRole_Call{Call: _e.mock.On("GetRole", roleID)}
}

func (_c *RoleServiceInterfaceMock_GetRole_Call) Run(run func(roleID string)) *RoleServiceInterfaceMock_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRole_Call) Return(role *Role, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRole_Call {
	_c.Call.Return(role, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRole_Call) RunAndReturn(run func(roleID string) (*Role, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleAssignments(roleID string, limit int, offset int) (*AssignmentListResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(roleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignments")
	}

	var r0 *AssignmentListResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, int, int) (*AssignmentListResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(roleID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) *AssignmentListResponse); ok {
		r0 = returnFunc(roleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AssignmentListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(roleID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignments'
type RoleServiceInterfaceMock_GetRoleAssignments_Call struct {
	*mock.Call
}

// GetRoleAssignments is a helper method to define mock.On call
//   - roleID string
//   - limit int
//   - offset int
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleAssignments(roleID interface{}, limit interface{}, offset interface{}) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	return &RoleServiceInterfaceMock_GetRoleAssignments_Call{Call: _e.mock.On("GetRoleAssignments", roleID, limit, offset)}
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) Run(run func(roleID string, limit int, offset int)) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) Return(assignmentListResponse *AssignmentListResponse, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(assignmentListResponse, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleAssignments_Call) RunAndReturn(run func(roleID string, limit int, offset int) (*AssignmentListResponse, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleList provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) GetRoleList(limit int, offset int) (*RoleListResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleList")
	}

	var r0 *RoleListResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(int, int) (*RoleListResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) *RoleListResponse); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RoleListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_GetRoleList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleList'
type RoleServiceInterfaceMock_GetRoleList_Call struct {
	*mock.Call
}

// GetRoleList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *RoleServiceInterfaceMock_Expecter) GetRoleList(limit interface{}, offset interface{}) *RoleServiceInterfaceMock_GetRoleList_Call {
	return &RoleServiceInterfaceMock_GetRoleList_Call{Call: _e.mock.On("GetRoleList", limit, offset)}
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) Run(run func(limit int, offset int)) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) Return(roleListResponse *RoleListResponse, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Return(roleListResponse, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_GetRoleList_Call) RunAndReturn(run func(limit int, offset int) (*RoleListResponse, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_GetRoleList_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAssignments provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) RemoveAssignments(roleID string, request AssignmentsRequest) *serviceerror.ServiceError {
	ret := _mock.Called(roleID, request)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, AssignmentsRequest) *serviceerror.ServiceError); ok {
		r0 = returnFunc(roleID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// RoleServiceInterfaceMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type RoleServiceInterfaceMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - roleID string
//   - request AssignmentsRequest
func (_e *RoleServiceInterfaceMock_Expecter) RemoveAssignments(roleID interface{}, request interface{}) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	return &RoleServiceInterfaceMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", roleID, request)}
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) Run(run func(roleID string, request AssignmentsRequest)) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 AssignmentsRequest
		if args[1] != nil {
			arg1 = args[1].(AssignmentsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) Return(serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_RemoveAssignments_Call) RunAndReturn(run func(roleID string, request AssignmentsRequest) *serviceerror.ServiceError) *RoleServiceInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type RoleServiceInterfaceMock
func (_mock *RoleServiceInterfaceMock) UpdateRole(roleID string, request UpdateRoleRequest) (*Role, *serviceerror.ServiceError) {
	ret := _mock.Called(roleID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *Role
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, UpdateRoleRequest) (*Role, *serviceerror.ServiceError)); ok {
		return returnFunc(roleID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(string, UpdateRoleRequest) *Role); ok {
		r0 = returnFunc(roleID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, UpdateRoleRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(roleID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// RoleServiceInterfaceMock_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type RoleServiceInterfaceMock_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - roleID string
//   - request UpdateRoleRequest
func (_e *RoleServiceInterfaceMock_Expecter) UpdateRole(roleID interface{}, request interface{}) *RoleServiceInterfaceMock_UpdateRole_Call {
	return &RoleServiceInterfaceMock_UpdateRole_Call{Call: _e.mock.On("UpdateRole", roleID, request)}
}

func (_c *RoleServiceInterfaceMock_UpdateRole_Call) Run(run func(roleID string, request UpdateRoleRequest)) *RoleServiceInterfaceMock_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 UpdateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(UpdateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleServiceInterfaceMock_UpdateRole_Call) Return(role *Role, serviceError *serviceerror.ServiceError) *RoleServiceInterfaceMock_UpdateRole_Call {
	_c.Call.Return(role, serviceError)
	return _c
}

func (_c *RoleServiceInterfaceMock_UpdateRole_Call) RunAndReturn(run func(roleID string, request UpdateRoleRequest) (*Role, *serviceerror.ServiceError)) *RoleServiceInterfaceMock_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
