// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role

import (
	mock "github.com/stretchr/testify/mock"
)

// newRoleStoreInterfaceMock creates a new instance of roleStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRoleStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *roleStoreInterfaceMock {
	mock := &roleStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// roleStoreInterfaceMock is an autogenerated mock type for the roleStoreInterface type
type roleStoreInterfaceMock struct {
	mock.Mock
}

type roleStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *roleStoreInterfaceMock) EXPECT() *roleStoreInterfaceMock_Expecter {
	return &roleStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddAssignments provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) AddAssignments(roleID string, assignments []Assignment) error {
	ret := _mock.Called(roleID, assignments)

	if len(ret) == 0 {
		panic("no return value specified for AddAssignments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []Assignment) error); ok {
		r0 = returnFunc(roleID, assignments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// roleStoreInterfaceMock_AddAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssignments'
type roleStoreInterfaceMock_AddAssignments_Call struct {
	*mock.Call
}

// AddAssignments is a helper method to define mock.On call
//   - roleID string
//   - assignments []Assignment
func (_e *roleStoreInterfaceMock_Expecter) AddAssignments(roleID interface{}, assignments interface{}) *roleStoreInterfaceMock_AddAssignments_Call {
	return &roleStoreInterfaceMock_AddAssignments_Call{Call: _e.mock.On("AddAssignments", roleID, assignments)}
}

func (_c *roleStoreInterfaceMock_AddAssignments_Call) Run(run func(roleID string, assignments []Assignment)) *roleStoreInterfaceMock_AddAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Assignment
		if args[1] != nil {
			arg1 = args[1].([]Assignment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_AddAssignments_Call) Return(err error) *roleStoreInterfaceMock_AddAssignments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *roleStoreInterfaceMock_AddAssignments_Call) RunAndReturn(run func(roleID string, assignments []Assignment) error) *roleStoreInterfaceMock_AddAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) CreateRole(role Role) error {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Role) error); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// roleStoreInterfaceMock_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type roleStoreInterfaceMock_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - role Role
func (_e *roleStoreInterfaceMock_Expecter) CreateRole(role interface{}) *roleStoreInterfaceMock_CreateRole_Call {
	return &roleStoreInterfaceMock_CreateRole_Call{Call: _e.mock.On("CreateRole", role)}
}

func (_c *roleStoreInterfaceMock_CreateRole_Call) Run(run func(role Role)) *roleStoreInterfaceMock_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Role
		if args[0] != nil {
			arg0 = args[0].(Role)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_CreateRole_Call) Return(err error) *roleStoreInterfaceMock_CreateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *roleStoreInterfaceMock_CreateRole_Call) RunAndReturn(run func(role Role) error) *roleStoreInterfaceMock_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) DeleteRole(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// roleStoreInterfaceMock_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type roleStoreInterfaceMock_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - id string
func (_e *roleStoreInterfaceMock_Expecter) DeleteRole(id interface{}) *roleStoreInterfaceMock_DeleteRole_Call {
	return &roleStoreInterfaceMock_DeleteRole_Call{Call: _e.mock.On("DeleteRole", id)}
}

func (_c *roleStoreInterfaceMock_DeleteRole_Call) Run(run func(id string)) *roleStoreInterfaceMock_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_DeleteRole_Call) Return(err error) *roleStoreInterfaceMock_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *roleStoreInterfaceMock_DeleteRole_Call) RunAndReturn(run func(id string) error) *roleStoreInterfaceMock_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) GetRole(id string) (Role, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Role, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Role); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(Role)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// roleStoreInterfaceMock_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type roleStoreInterfaceMock_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - id string
func (_e *roleStoreInterfaceMock_Expecter) GetRole(id interface{}) *roleStoreInterfaceMock_GetRole_Call {
	return &roleStoreInterfaceMock_GetRole_Call{Call: _e.mock.On("GetRole", id)}
}

func (_c *roleStoreInterfaceMock_GetRole_Call) Run(run func(id string)) *roleStoreInterfaceMock_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_GetRole_Call) Return(role Role, err error) *roleStoreInterfaceMock_GetRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *roleStoreInterfaceMock_GetRole_Call) RunAndReturn(run func(id string) (Role, error)) *roleStoreInterfaceMock_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignments provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) GetRoleAssignments(roleID string, limit int, offset int) ([]Assignment, error) {
	ret := _mock.Called(roleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignments")
	}

	var r0 []Assignment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]Assignment, error)); ok {
		return returnFunc(roleID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []Assignment); ok {
		r0 = returnFunc(roleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Assignment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(roleID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// roleStoreInterfaceMock_GetRoleAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignments'
type roleStoreInterfaceMock_GetRoleAssignments_Call struct {
	*mock.Call
}

// GetRoleAssignments is a helper method to define mock.On call
//   - roleID string
//   - limit int
//   - offset int
func (_e *roleStoreInterfaceMock_Expecter) GetRoleAssignments(roleID interface{}, limit interface{}, offset interface{}) *roleStoreInterfaceMock_GetRoleAssignments_Call {
	return &roleStoreInterfaceMock_GetRoleAssignments_Call{Call: _e.mock.On("GetRoleAssignments", roleID, limit, offset)}
}

func (_c *roleStoreInterfaceMock_GetRoleAssignments_Call) Run(run func(roleID string, limit int, offset int)) *roleStoreInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleAssignments_Call) Return(assignments []Assignment, err error) *roleStoreInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(assignments, err)
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleAssignments_Call) RunAndReturn(run func(roleID string, limit int, offset int) ([]Assignment, error)) *roleStoreInterfaceMock_GetRoleAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAssignmentsCount provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) GetRoleAssignmentsCount(roleID string) (int, error) {
	ret := _mock.Called(roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAssignmentsCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(roleID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// roleStoreInterfaceMock_GetRoleAssignmentsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAssignmentsCount'
type roleStoreInterfaceMock_GetRoleAssignmentsCount_Call struct {
	*mock.Call
}

// GetRoleAssignmentsCount is a helper method to define mock.On call
//   - roleID string
func (_e *roleStoreInterfaceMock_Expecter) GetRoleAssignmentsCount(roleID interface{}) *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call {
	return &roleStoreInterfaceMock_GetRoleAssignmentsCount_Call{Call: _e.mock.On("GetRoleAssignmentsCount", roleID)}
}

func (_c *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call) Run(run func(roleID string)) *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call) Return(n int, err error) *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call) RunAndReturn(run func(roleID string) (int, error)) *roleStoreInterfaceMock_GetRoleAssignmentsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleList provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) GetRoleList(limit int, offset int) ([]RoleSummary, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleList")
	}

	var r0 []RoleSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]RoleSummary, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []RoleSummary); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RoleSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// roleStoreInterfaceMock_GetRoleList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleList'
type roleStoreInterfaceMock_GetRoleList_Call struct {
	*mock.Call
}

// GetRoleList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *roleStoreInterfaceMock_Expecter) GetRoleList(limit interface{}, offset interface{}) *roleStoreInterfaceMock_GetRoleList_Call {
	return &roleStoreInterfaceMock_GetRoleList_Call{Call: _e.mock.On("GetRoleList", limit, offset)}
}

func (_c *roleStoreInterfaceMock_GetRoleList_Call) Run(run func(limit int, offset int)) *roleStoreInterfaceMock_GetRoleList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleList_Call) Return(roleSummarys []RoleSummary, err error) *roleStoreInterfaceMock_GetRoleList_Call {
	_c.Call.Return(roleSummarys, err)
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleList_Call) RunAndReturn(run func(limit int, offset int) ([]RoleSummary, error)) *roleStoreInterfaceMock_GetRoleList_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleListCount provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) GetRoleListCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoleListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// roleStoreInterfaceMock_GetRoleListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleListCount'
type roleStoreInterfaceMock_GetRoleListCount_Call struct {
	*mock.Call
}

// GetRoleListCount is a helper method to define mock.On call
func (_e *roleStoreInterfaceMock_Expecter) GetRoleListCount() *roleStoreInterfaceMock_GetRoleListCount_Call {
	return &roleStoreInterfaceMock_GetRoleListCount_Call{Call: _e.mock.On("GetRoleListCount")}
}

func (_c *roleStoreInterfaceMock_GetRoleListCount_Call) Run(run func()) *roleStoreInterfaceMock_GetRoleListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleListCount_Call) Return(n int, err error) *roleStoreInterfaceMock_GetRoleListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *roleStoreInterfaceMock_GetRoleListCount_Call) RunAndReturn(run func() (int, error)) *roleStoreInterfaceMock_GetRoleListCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAssignments provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) RemoveAssignments(roleID string, assignments []Assignment) error {
	ret := _mock.Called(roleID, assignments)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAssignments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []Assignment) error); ok {
		r0 = returnFunc(roleID, assignments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// roleStoreInterfaceMock_RemoveAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAssignments'
type roleStoreInterfaceMock_RemoveAssignments_Call struct {
	*mock.Call
}

// RemoveAssignments is a helper method to define mock.On call
//   - roleID string
//   - assignments []Assignment
func (_e *roleStoreInterfaceMock_Expecter) RemoveAssignments(roleID interface{}, assignments interface{}) *roleStoreInterfaceMock_RemoveAssignments_Call {
	return &roleStoreInterfaceMock_RemoveAssignments_Call{Call: _e.mock.On("RemoveAssignments", roleID, assignments)}
}

func (_c *roleStoreInterfaceMock_RemoveAssignments_Call) Run(run func(roleID string, assignments []Assignment)) *roleStoreInterfaceMock_RemoveAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Assignment
		if args[1] != nil {
			arg1 = args[1].([]Assignment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_RemoveAssignments_Call) Return(err error) *roleStoreInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *roleStoreInterfaceMock_RemoveAssignments_Call) RunAndReturn(run func(roleID string, assignments []Assignment) error) *roleStoreInterfaceMock_RemoveAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type roleStoreInterfaceMock
func (_mock *roleStoreInterfaceMock) UpdateRole(role Role) error {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Role) error); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// roleStoreInterfaceMock_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type roleStoreInterfaceMock_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - role Role
func (_e *roleStoreInterfaceMock_Expecter) UpdateRole(role interface{}) *roleStoreInterfaceMock_UpdateRole_Call {
	return &roleStoreInterfaceMock_UpdateRole_Call{Call: _e.mock.On("UpdateRole", role)}
}

func (_c *roleStoreInterfaceMock_UpdateRole_Call) Run(run func(role Role)) *roleStoreInterfaceMock_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Role
		if args[0] != nil {
			arg0 = args[0].(Role)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *roleStoreInterfaceMock_UpdateRole_Call) Return(err error) *roleStoreInterfaceMock_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *roleStoreInterfaceMock_UpdateRole_Call) RunAndReturn(run func(role Role) error) *roleStoreInterfaceMock_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
