// Code generated by mockery v2.53.4. DO NOT EDIT.

package storemock

import (
	model "github.com/asgardeo/thunder/internal/oauth/oauth2/authz/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthorizationCodeStoreInterface is an autogenerated mock type for the AuthorizationCodeStoreInterface type
type MockAuthorizationCodeStoreInterface struct {
	mock.Mock
}

type MockAuthorizationCodeStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationCodeStoreInterface) EXPECT() *MockAuthorizationCodeStoreInterface_Expecter {
	return &MockAuthorizationCodeStoreInterface_Expecter{mock: &_m.Mock}
}

// DeactivateAuthorizationCode provides a mock function with given fields: authzCode
func (_m *MockAuthorizationCodeStoreInterface) DeactivateAuthorizationCode(authzCode model.AuthorizationCode) error {
	ret := _m.Called(authzCode)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateAuthorizationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.AuthorizationCode) error); ok {
		r0 = rf(authzCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateAuthorizationCode'
type MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call struct {
	*mock.Call
}

// DeactivateAuthorizationCode is a helper method to define mock.On call
//   - authzCode model.AuthorizationCode
func (_e *MockAuthorizationCodeStoreInterface_Expecter) DeactivateAuthorizationCode(authzCode interface{}) *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call {
	return &MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call{Call: _e.mock.On("DeactivateAuthorizationCode", authzCode)}
}

func (_c *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call) Run(run func(authzCode model.AuthorizationCode)) *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.AuthorizationCode))
	})
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call) Return(_a0 error) *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call) RunAndReturn(run func(model.AuthorizationCode) error) *MockAuthorizationCodeStoreInterface_DeactivateAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireAuthorizationCode provides a mock function with given fields: authzCode
func (_m *MockAuthorizationCodeStoreInterface) ExpireAuthorizationCode(authzCode model.AuthorizationCode) error {
	ret := _m.Called(authzCode)

	if len(ret) == 0 {
		panic("no return value specified for ExpireAuthorizationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.AuthorizationCode) error); ok {
		r0 = rf(authzCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireAuthorizationCode'
type MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call struct {
	*mock.Call
}

// ExpireAuthorizationCode is a helper method to define mock.On call
//   - authzCode model.AuthorizationCode
func (_e *MockAuthorizationCodeStoreInterface_Expecter) ExpireAuthorizationCode(authzCode interface{}) *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call {
	return &MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call{Call: _e.mock.On("ExpireAuthorizationCode", authzCode)}
}

func (_c *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call) Run(run func(authzCode model.AuthorizationCode)) *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.AuthorizationCode))
	})
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call) Return(_a0 error) *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call) RunAndReturn(run func(model.AuthorizationCode) error) *MockAuthorizationCodeStoreInterface_ExpireAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationCode provides a mock function with given fields: clientID, authCode
func (_m *MockAuthorizationCodeStoreInterface) GetAuthorizationCode(clientID string, authCode string) (model.AuthorizationCode, error) {
	ret := _m.Called(clientID, authCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationCode")
	}

	var r0 model.AuthorizationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (model.AuthorizationCode, error)); ok {
		return rf(clientID, authCode)
	}
	if rf, ok := ret.Get(0).(func(string, string) model.AuthorizationCode); ok {
		r0 = rf(clientID, authCode)
	} else {
		r0 = ret.Get(0).(model.AuthorizationCode)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientID, authCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationCode'
type MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call struct {
	*mock.Call
}

// GetAuthorizationCode is a helper method to define mock.On call
//   - clientID string
//   - authCode string
func (_e *MockAuthorizationCodeStoreInterface_Expecter) GetAuthorizationCode(clientID interface{}, authCode interface{}) *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call {
	return &MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call{Call: _e.mock.On("GetAuthorizationCode", clientID, authCode)}
}

func (_c *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call) Run(run func(clientID string, authCode string)) *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call) Return(_a0 model.AuthorizationCode, _a1 error) *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call) RunAndReturn(run func(string, string) (model.AuthorizationCode, error)) *MockAuthorizationCodeStoreInterface_GetAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAuthorizationCode provides a mock function with given fields: authzCode
func (_m *MockAuthorizationCodeStoreInterface) InsertAuthorizationCode(authzCode model.AuthorizationCode) error {
	ret := _m.Called(authzCode)

	if len(ret) == 0 {
		panic("no return value specified for InsertAuthorizationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.AuthorizationCode) error); ok {
		r0 = rf(authzCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAuthorizationCode'
type MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call struct {
	*mock.Call
}

// InsertAuthorizationCode is a helper method to define mock.On call
//   - authzCode model.AuthorizationCode
func (_e *MockAuthorizationCodeStoreInterface_Expecter) InsertAuthorizationCode(authzCode interface{}) *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call {
	return &MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call{Call: _e.mock.On("InsertAuthorizationCode", authzCode)}
}

func (_c *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call) Run(run func(authzCode model.AuthorizationCode)) *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.AuthorizationCode))
	})
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call) Return(_a0 error) *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call) RunAndReturn(run func(model.AuthorizationCode) error) *MockAuthorizationCodeStoreInterface_InsertAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAuthorizationCode provides a mock function with given fields: authzCode
func (_m *MockAuthorizationCodeStoreInterface) RevokeAuthorizationCode(authzCode model.AuthorizationCode) error {
	ret := _m.Called(authzCode)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAuthorizationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.AuthorizationCode) error); ok {
		r0 = rf(authzCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAuthorizationCode'
type MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call struct {
	*mock.Call
}

// RevokeAuthorizationCode is a helper method to define mock.On call
//   - authzCode model.AuthorizationCode
func (_e *MockAuthorizationCodeStoreInterface_Expecter) RevokeAuthorizationCode(authzCode interface{}) *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call {
	return &MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call{Call: _e.mock.On("RevokeAuthorizationCode", authzCode)}
}

func (_c *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call) Run(run func(authzCode model.AuthorizationCode)) *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.AuthorizationCode))
	})
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call) Return(_a0 error) *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call) RunAndReturn(run func(model.AuthorizationCode) error) *MockAuthorizationCodeStoreInterface_RevokeAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizationCodeStoreInterface creates a new instance of MockAuthorizationCodeStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizationCodeStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizationCodeStoreInterface {
	mock := &MockAuthorizationCodeStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
