// Code generated by mockery v2.53.4. DO NOT EDIT.

package certmock

import (
	constants "github.com/asgardeo/thunder/internal/cert/constants"
	mock "github.com/stretchr/testify/mock"

	model "github.com/asgardeo/thunder/internal/cert/model"

	serviceerror "github.com/asgardeo/thunder/internal/system/error/serviceerror"
)

// MockCertificateServiceInterface is an autogenerated mock type for the CertificateServiceInterface type
type MockCertificateServiceInterface struct {
	mock.Mock
}

type MockCertificateServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateServiceInterface) EXPECT() *MockCertificateServiceInterface_Expecter {
	return &MockCertificateServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateCertificate provides a mock function with given fields: _a0
func (_m *MockCertificateServiceInterface) CreateCertificate(_a0 *model.Certificate) (*model.Certificate, *serviceerror.ServiceError) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 *model.Certificate
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(*model.Certificate) (*model.Certificate, *serviceerror.ServiceError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.Certificate) *model.Certificate); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Certificate) *serviceerror.ServiceError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockCertificateServiceInterface_CreateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCertificate'
type MockCertificateServiceInterface_CreateCertificate_Call struct {
	*mock.Call
}

// CreateCertificate is a helper method to define mock.On call
//   - _a0 *model.Certificate
func (_e *MockCertificateServiceInterface_Expecter) CreateCertificate(_a0 interface{}) *MockCertificateServiceInterface_CreateCertificate_Call {
	return &MockCertificateServiceInterface_CreateCertificate_Call{Call: _e.mock.On("CreateCertificate", _a0)}
}

func (_c *MockCertificateServiceInterface_CreateCertificate_Call) Run(run func(_a0 *model.Certificate)) *MockCertificateServiceInterface_CreateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Certificate))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_CreateCertificate_Call) Return(_a0 *model.Certificate, _a1 *serviceerror.ServiceError) *MockCertificateServiceInterface_CreateCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateServiceInterface_CreateCertificate_Call) RunAndReturn(run func(*model.Certificate) (*model.Certificate, *serviceerror.ServiceError)) *MockCertificateServiceInterface_CreateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificateByID provides a mock function with given fields: id
func (_m *MockCertificateServiceInterface) DeleteCertificateByID(id string) *serviceerror.ServiceError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificateByID")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// MockCertificateServiceInterface_DeleteCertificateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificateByID'
type MockCertificateServiceInterface_DeleteCertificateByID_Call struct {
	*mock.Call
}

// DeleteCertificateByID is a helper method to define mock.On call
//   - id string
func (_e *MockCertificateServiceInterface_Expecter) DeleteCertificateByID(id interface{}) *MockCertificateServiceInterface_DeleteCertificateByID_Call {
	return &MockCertificateServiceInterface_DeleteCertificateByID_Call{Call: _e.mock.On("DeleteCertificateByID", id)}
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByID_Call) Run(run func(id string)) *MockCertificateServiceInterface_DeleteCertificateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByID_Call) Return(_a0 *serviceerror.ServiceError) *MockCertificateServiceInterface_DeleteCertificateByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByID_Call) RunAndReturn(run func(string) *serviceerror.ServiceError) *MockCertificateServiceInterface_DeleteCertificateByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificateByReference provides a mock function with given fields: refType, refID
func (_m *MockCertificateServiceInterface) DeleteCertificateByReference(refType constants.CertificateReferenceType, refID string) *serviceerror.ServiceError {
	ret := _m.Called(refType, refID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificateByReference")
	}

	var r0 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(constants.CertificateReferenceType, string) *serviceerror.ServiceError); ok {
		r0 = rf(refType, refID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}

	return r0
}

// MockCertificateServiceInterface_DeleteCertificateByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificateByReference'
type MockCertificateServiceInterface_DeleteCertificateByReference_Call struct {
	*mock.Call
}

// DeleteCertificateByReference is a helper method to define mock.On call
//   - refType constants.CertificateReferenceType
//   - refID string
func (_e *MockCertificateServiceInterface_Expecter) DeleteCertificateByReference(refType interface{}, refID interface{}) *MockCertificateServiceInterface_DeleteCertificateByReference_Call {
	return &MockCertificateServiceInterface_DeleteCertificateByReference_Call{Call: _e.mock.On("DeleteCertificateByReference", refType, refID)}
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByReference_Call) Run(run func(refType constants.CertificateReferenceType, refID string)) *MockCertificateServiceInterface_DeleteCertificateByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(constants.CertificateReferenceType), args[1].(string))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByReference_Call) Return(_a0 *serviceerror.ServiceError) *MockCertificateServiceInterface_DeleteCertificateByReference_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateServiceInterface_DeleteCertificateByReference_Call) RunAndReturn(run func(constants.CertificateReferenceType, string) *serviceerror.ServiceError) *MockCertificateServiceInterface_DeleteCertificateByReference_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateByID provides a mock function with given fields: id
func (_m *MockCertificateServiceInterface) GetCertificateByID(id string) (*model.Certificate, *serviceerror.ServiceError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByID")
	}

	var r0 *model.Certificate
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string) (*model.Certificate, *serviceerror.ServiceError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Certificate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockCertificateServiceInterface_GetCertificateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByID'
type MockCertificateServiceInterface_GetCertificateByID_Call struct {
	*mock.Call
}

// GetCertificateByID is a helper method to define mock.On call
//   - id string
func (_e *MockCertificateServiceInterface_Expecter) GetCertificateByID(id interface{}) *MockCertificateServiceInterface_GetCertificateByID_Call {
	return &MockCertificateServiceInterface_GetCertificateByID_Call{Call: _e.mock.On("GetCertificateByID", id)}
}

func (_c *MockCertificateServiceInterface_GetCertificateByID_Call) Run(run func(id string)) *MockCertificateServiceInterface_GetCertificateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_GetCertificateByID_Call) Return(_a0 *model.Certificate, _a1 *serviceerror.ServiceError) *MockCertificateServiceInterface_GetCertificateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateServiceInterface_GetCertificateByID_Call) RunAndReturn(run func(string) (*model.Certificate, *serviceerror.ServiceError)) *MockCertificateServiceInterface_GetCertificateByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateByReference provides a mock function with given fields: refType, refID
func (_m *MockCertificateServiceInterface) GetCertificateByReference(refType constants.CertificateReferenceType, refID string) (*model.Certificate, *serviceerror.ServiceError) {
	ret := _m.Called(refType, refID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByReference")
	}

	var r0 *model.Certificate
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(constants.CertificateReferenceType, string) (*model.Certificate, *serviceerror.ServiceError)); ok {
		return rf(refType, refID)
	}
	if rf, ok := ret.Get(0).(func(constants.CertificateReferenceType, string) *model.Certificate); ok {
		r0 = rf(refType, refID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(constants.CertificateReferenceType, string) *serviceerror.ServiceError); ok {
		r1 = rf(refType, refID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockCertificateServiceInterface_GetCertificateByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByReference'
type MockCertificateServiceInterface_GetCertificateByReference_Call struct {
	*mock.Call
}

// GetCertificateByReference is a helper method to define mock.On call
//   - refType constants.CertificateReferenceType
//   - refID string
func (_e *MockCertificateServiceInterface_Expecter) GetCertificateByReference(refType interface{}, refID interface{}) *MockCertificateServiceInterface_GetCertificateByReference_Call {
	return &MockCertificateServiceInterface_GetCertificateByReference_Call{Call: _e.mock.On("GetCertificateByReference", refType, refID)}
}

func (_c *MockCertificateServiceInterface_GetCertificateByReference_Call) Run(run func(refType constants.CertificateReferenceType, refID string)) *MockCertificateServiceInterface_GetCertificateByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(constants.CertificateReferenceType), args[1].(string))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_GetCertificateByReference_Call) Return(_a0 *model.Certificate, _a1 *serviceerror.ServiceError) *MockCertificateServiceInterface_GetCertificateByReference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateServiceInterface_GetCertificateByReference_Call) RunAndReturn(run func(constants.CertificateReferenceType, string) (*model.Certificate, *serviceerror.ServiceError)) *MockCertificateServiceInterface_GetCertificateByReference_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificateByID provides a mock function with given fields: id, _a1
func (_m *MockCertificateServiceInterface) UpdateCertificateByID(id string, _a1 *model.Certificate) (*model.Certificate, *serviceerror.ServiceError) {
	ret := _m.Called(id, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificateByID")
	}

	var r0 *model.Certificate
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(string, *model.Certificate) (*model.Certificate, *serviceerror.ServiceError)); ok {
		return rf(id, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *model.Certificate) *model.Certificate); ok {
		r0 = rf(id, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.Certificate) *serviceerror.ServiceError); ok {
		r1 = rf(id, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockCertificateServiceInterface_UpdateCertificateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificateByID'
type MockCertificateServiceInterface_UpdateCertificateByID_Call struct {
	*mock.Call
}

// UpdateCertificateByID is a helper method to define mock.On call
//   - id string
//   - _a1 *model.Certificate
func (_e *MockCertificateServiceInterface_Expecter) UpdateCertificateByID(id interface{}, _a1 interface{}) *MockCertificateServiceInterface_UpdateCertificateByID_Call {
	return &MockCertificateServiceInterface_UpdateCertificateByID_Call{Call: _e.mock.On("UpdateCertificateByID", id, _a1)}
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByID_Call) Run(run func(id string, _a1 *model.Certificate)) *MockCertificateServiceInterface_UpdateCertificateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.Certificate))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByID_Call) Return(_a0 *model.Certificate, _a1 *serviceerror.ServiceError) *MockCertificateServiceInterface_UpdateCertificateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByID_Call) RunAndReturn(run func(string, *model.Certificate) (*model.Certificate, *serviceerror.ServiceError)) *MockCertificateServiceInterface_UpdateCertificateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificateByReference provides a mock function with given fields: refType, refID, _a2
func (_m *MockCertificateServiceInterface) UpdateCertificateByReference(refType constants.CertificateReferenceType, refID string, _a2 *model.Certificate) (*model.Certificate, *serviceerror.ServiceError) {
	ret := _m.Called(refType, refID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificateByReference")
	}

	var r0 *model.Certificate
	var r1 *serviceerror.ServiceError
	if rf, ok := ret.Get(0).(func(constants.CertificateReferenceType, string, *model.Certificate) (*model.Certificate, *serviceerror.ServiceError)); ok {
		return rf(refType, refID, _a2)
	}
	if rf, ok := ret.Get(0).(func(constants.CertificateReferenceType, string, *model.Certificate) *model.Certificate); ok {
		r0 = rf(refType, refID, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(constants.CertificateReferenceType, string, *model.Certificate) *serviceerror.ServiceError); ok {
		r1 = rf(refType, refID, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}

	return r0, r1
}

// MockCertificateServiceInterface_UpdateCertificateByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificateByReference'
type MockCertificateServiceInterface_UpdateCertificateByReference_Call struct {
	*mock.Call
}

// UpdateCertificateByReference is a helper method to define mock.On call
//   - refType constants.CertificateReferenceType
//   - refID string
//   - _a2 *model.Certificate
func (_e *MockCertificateServiceInterface_Expecter) UpdateCertificateByReference(refType interface{}, refID interface{}, _a2 interface{}) *MockCertificateServiceInterface_UpdateCertificateByReference_Call {
	return &MockCertificateServiceInterface_UpdateCertificateByReference_Call{Call: _e.mock.On("UpdateCertificateByReference", refType, refID, _a2)}
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByReference_Call) Run(run func(refType constants.CertificateReferenceType, refID string, _a2 *model.Certificate)) *MockCertificateServiceInterface_UpdateCertificateByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(constants.CertificateReferenceType), args[1].(string), args[2].(*model.Certificate))
	})
	return _c
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByReference_Call) Return(_a0 *model.Certificate, _a1 *serviceerror.ServiceError) *MockCertificateServiceInterface_UpdateCertificateByReference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateServiceInterface_UpdateCertificateByReference_Call) RunAndReturn(run func(constants.CertificateReferenceType, string, *model.Certificate) (*model.Certificate, *serviceerror.ServiceError)) *MockCertificateServiceInterface_UpdateCertificateByReference_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertificateServiceInterface creates a new instance of MockCertificateServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateServiceInterface {
	mock := &MockCertificateServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
