// Code generated by mockery v2.53.4. DO NOT EDIT.

package cert

import (
	config "github.com/asgardeo/thunder/internal/system/config"
	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// MockSystemCertificateServiceInterface is an autogenerated mock type for the SystemCertificateServiceInterface type
type MockSystemCertificateServiceInterface struct {
	mock.Mock
}

type MockSystemCertificateServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemCertificateServiceInterface) EXPECT() *MockSystemCertificateServiceInterface_Expecter {
	return &MockSystemCertificateServiceInterface_Expecter{mock: &_m.Mock}
}

// GetCertificateKid provides a mock function with no fields
func (_m *MockSystemCertificateServiceInterface) GetCertificateKid() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateKid")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemCertificateServiceInterface_GetCertificateKid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateKid'
type MockSystemCertificateServiceInterface_GetCertificateKid_Call struct {
	*mock.Call
}

// GetCertificateKid is a helper method to define mock.On call
func (_e *MockSystemCertificateServiceInterface_Expecter) GetCertificateKid() *MockSystemCertificateServiceInterface_GetCertificateKid_Call {
	return &MockSystemCertificateServiceInterface_GetCertificateKid_Call{Call: _e.mock.On("GetCertificateKid")}
}

func (_c *MockSystemCertificateServiceInterface_GetCertificateKid_Call) Run(run func()) *MockSystemCertificateServiceInterface_GetCertificateKid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemCertificateServiceInterface_GetCertificateKid_Call) Return(_a0 string, _a1 error) *MockSystemCertificateServiceInterface_GetCertificateKid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemCertificateServiceInterface_GetCertificateKid_Call) RunAndReturn(run func() (string, error)) *MockSystemCertificateServiceInterface_GetCertificateKid_Call {
	_c.Call.Return(run)
	return _c
}

// GetTLSConfig provides a mock function with given fields: cfg, currentDirectory
func (_m *MockSystemCertificateServiceInterface) GetTLSConfig(cfg *config.Config, currentDirectory string) (*tls.Config, error) {
	ret := _m.Called(cfg, currentDirectory)

	if len(ret) == 0 {
		panic("no return value specified for GetTLSConfig")
	}

	var r0 *tls.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(*config.Config, string) (*tls.Config, error)); ok {
		return rf(cfg, currentDirectory)
	}
	if rf, ok := ret.Get(0).(func(*config.Config, string) *tls.Config); ok {
		r0 = rf(cfg, currentDirectory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(*config.Config, string) error); ok {
		r1 = rf(cfg, currentDirectory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemCertificateServiceInterface_GetTLSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTLSConfig'
type MockSystemCertificateServiceInterface_GetTLSConfig_Call struct {
	*mock.Call
}

// GetTLSConfig is a helper method to define mock.On call
//   - cfg *config.Config
//   - currentDirectory string
func (_e *MockSystemCertificateServiceInterface_Expecter) GetTLSConfig(cfg interface{}, currentDirectory interface{}) *MockSystemCertificateServiceInterface_GetTLSConfig_Call {
	return &MockSystemCertificateServiceInterface_GetTLSConfig_Call{Call: _e.mock.On("GetTLSConfig", cfg, currentDirectory)}
}

func (_c *MockSystemCertificateServiceInterface_GetTLSConfig_Call) Run(run func(cfg *config.Config, currentDirectory string)) *MockSystemCertificateServiceInterface_GetTLSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Config), args[1].(string))
	})
	return _c
}

func (_c *MockSystemCertificateServiceInterface_GetTLSConfig_Call) Return(_a0 *tls.Config, _a1 error) *MockSystemCertificateServiceInterface_GetTLSConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemCertificateServiceInterface_GetTLSConfig_Call) RunAndReturn(run func(*config.Config, string) (*tls.Config, error)) *MockSystemCertificateServiceInterface_GetTLSConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemCertificateServiceInterface creates a new instance of MockSystemCertificateServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemCertificateServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemCertificateServiceInterface {
	mock := &MockSystemCertificateServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
