// Code generated by mockery v2.53.4. DO NOT EDIT.

package provider

import (
	mock "github.com/stretchr/testify/mock"

	validator "github.com/asgardeo/thunder/internal/oauth/scope/validator"
)

// MockScopeValidatorProviderInterface is an autogenerated mock type for the ScopeValidatorProviderInterface type
type MockScopeValidatorProviderInterface struct {
	mock.Mock
}

type MockScopeValidatorProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScopeValidatorProviderInterface) EXPECT() *MockScopeValidatorProviderInterface_Expecter {
	return &MockScopeValidatorProviderInterface_Expecter{mock: &_m.Mock}
}

// GetScopeValidator provides a mock function with no fields
func (_m *MockScopeValidatorProviderInterface) GetScopeValidator() validator.ScopeValidatorInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetScopeValidator")
	}

	var r0 validator.ScopeValidatorInterface
	if rf, ok := ret.Get(0).(func() validator.ScopeValidatorInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validator.ScopeValidatorInterface)
		}
	}

	return r0
}

// MockScopeValidatorProviderInterface_GetScopeValidator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScopeValidator'
type MockScopeValidatorProviderInterface_GetScopeValidator_Call struct {
	*mock.Call
}

// GetScopeValidator is a helper method to define mock.On call
func (_e *MockScopeValidatorProviderInterface_Expecter) GetScopeValidator() *MockScopeValidatorProviderInterface_GetScopeValidator_Call {
	return &MockScopeValidatorProviderInterface_GetScopeValidator_Call{Call: _e.mock.On("GetScopeValidator")}
}

func (_c *MockScopeValidatorProviderInterface_GetScopeValidator_Call) Run(run func()) *MockScopeValidatorProviderInterface_GetScopeValidator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScopeValidatorProviderInterface_GetScopeValidator_Call) Return(_a0 validator.ScopeValidatorInterface) *MockScopeValidatorProviderInterface_GetScopeValidator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScopeValidatorProviderInterface_GetScopeValidator_Call) RunAndReturn(run func() validator.ScopeValidatorInterface) *MockScopeValidatorProviderInterface_GetScopeValidator_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScopeValidatorProviderInterface creates a new instance of MockScopeValidatorProviderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScopeValidatorProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScopeValidatorProviderInterface {
	mock := &MockScopeValidatorProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
