// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package magiclinkmock

import (
	"context"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/userprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewMagicLinkAuthnServiceInterfaceMock creates a new instance of MagicLinkAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMagicLinkAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MagicLinkAuthnServiceInterfaceMock {
	mock := &MagicLinkAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MagicLinkAuthnServiceInterfaceMock is an autogenerated mock type for the MagicLinkAuthnServiceInterface type
type MagicLinkAuthnServiceInterfaceMock struct {
	mock.Mock
}

type MagicLinkAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MagicLinkAuthnServiceInterfaceMock) EXPECT() *MagicLinkAuthnServiceInterfaceMock_Expecter {
	return &MagicLinkAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// SendMagicLink provides a mock function for the type MagicLinkAuthnServiceInterfaceMock
func (_mock *MagicLinkAuthnServiceInterfaceMock) SendMagicLink(ctx context.Context, recipient string, expirySeconds int64, flowID string, magicLinkURL *string) *serviceerror.I18nServiceError {
	ret := _mock.Called(ctx, recipient, expirySeconds, flowID, magicLinkURL)

	if len(ret) == 0 {
		panic("no return value specified for SendMagicLink")
	}

	var r0 *serviceerror.I18nServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, *string) *serviceerror.I18nServiceError); ok {
		r0 = returnFunc(ctx, recipient, expirySeconds, flowID, magicLinkURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.I18nServiceError)
		}
	}
	return r0
}

// MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLink'
type MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call struct {
	*mock.Call
}

// SendMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - expirySeconds int64
//   - flowID string
//   - magicLinkURL *string
func (_e *MagicLinkAuthnServiceInterfaceMock_Expecter) SendMagicLink(ctx interface{}, recipient interface{}, expirySeconds interface{}, flowID interface{}, magicLinkURL interface{}) *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call {
	return &MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call{Call: _e.mock.On("SendMagicLink", ctx, recipient, expirySeconds, flowID, magicLinkURL)}
}

func (_c *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call) Run(run func(ctx context.Context, recipient string, expirySeconds int64, flowID string, magicLinkURL *string)) *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call) Return(i18nServiceError *serviceerror.I18nServiceError) *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call {
	_c.Call.Return(i18nServiceError)
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call) RunAndReturn(run func(ctx context.Context, recipient string, expirySeconds int64, flowID string, magicLinkURL *string) *serviceerror.I18nServiceError) *MagicLinkAuthnServiceInterfaceMock_SendMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMagicLink provides a mock function for the type MagicLinkAuthnServiceInterfaceMock
func (_mock *MagicLinkAuthnServiceInterfaceMock) VerifyMagicLink(ctx context.Context, token string) (*userprovider.User, *serviceerror.I18nServiceError) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMagicLink")
	}

	var r0 *userprovider.User
	var r1 *serviceerror.I18nServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*userprovider.User, *serviceerror.I18nServiceError)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *userprovider.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.I18nServiceError); ok {
		r1 = returnFunc(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.I18nServiceError)
		}
	}
	return r0, r1
}

// MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMagicLink'
type MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call struct {
	*mock.Call
}

// VerifyMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MagicLinkAuthnServiceInterfaceMock_Expecter) VerifyMagicLink(ctx interface{}, token interface{}) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	return &MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call{Call: _e.mock.On("VerifyMagicLink", ctx, token)}
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) Run(run func(ctx context.Context, token string)) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) Return(user *userprovider.User, i18nServiceError *serviceerror.I18nServiceError) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Return(user, i18nServiceError)
	return _c
}

func (_c *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call) RunAndReturn(run func(ctx context.Context, token string) (*userprovider.User, *serviceerror.I18nServiceError)) *MagicLinkAuthnServiceInterfaceMock_VerifyMagicLink_Call {
	_c.Call.Return(run)
	return _c
}
