openapi: 3.0.3

info:
  title: Identity Provider Management API
  description: This API is used to manage identity providers.
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "8090"

paths:
  /identity-providers:
    get:
      summary: List identity providers
      description: Retrieve a list of all identity providers.
      tags:
      - Identity Providers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDPListResponse'
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    post:
      summary: Create an identity provider
      description: Creates a new identity provider with the provided details.
      tags:
      - Identity Providers
      requestBody:
        description: Identity provider data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IDPRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDPResponse'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1007"
                message: "Invalid request format"
                description: "The request body is malformed or contains invalid data"
        "409":
          description: 'Conflict: An identity provider with the same name already exists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1004"
                message: "Identity provider already exists"
                description: "An identity provider with the same name already exists"
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /identity-providers/{id}:
    get:
      summary: Get an identity provider by ID
      description: Retrieve a specific identity provider using its ID.
      tags:
      - Identity Providers
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDPResponse'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1002"
                message: "Invalid identity provider ID"
                description: "The provided identity provider ID is invalid or empty"
        "404":
          description: 'Not Found: The identity provider with the specified ID does not exist.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1001"
                message: "Identity provider not found"
                description: "The requested identity provider could not be found"
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    put:
      summary: Update an identity provider
      description: Update the details of an existing identity provider.
      tags:
      - Identity Providers
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      requestBody:
        description: Updated identity provider data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IDPRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDPResponse'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1002"
                message: "Invalid identity provider ID"
                description: "The provided identity provider ID is invalid or empty"
        "404":
          description: 'Not Found: The identity provider with the specified ID does not exist.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1001"
                message: "Identity provider not found"
                description: "The requested identity provider could not be found"
        "409":
          description: 'Conflict: An identity provider with the same name already exists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1004"
                message: "Identity provider already exists"
                description: "An identity provider with the same name already exists"
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

    delete:
      summary: Delete an identity provider
      description: Delete an identity provider using its ID.
      tags:
      - Identity Providers
      parameters:
      - name: id
        in: path
        description: Identity provider ID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'
              example:
                code: "IDP-1002"
                message: "Invalid identity provider ID"
                description: "The provided identity provider ID is invalid or empty"
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:
    IDPRequest:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: Name of the identity provider
          example: "Google"
        description:
          type: string
          description: Description of the identity provider
          example: "Google OIDC identity provider for employee authentication"
        type:
          type: string
          description: Type of the identity provider (e.g., OAUTH)
          example: "GOOGLE"
          enum:
            - OAUTH
            - OIDC
            - GOOGLE
            - GITHUB
        properties:
          type: array
          items:
            $ref: '#/components/schemas/IDPProperty'
          description: Properties of the identity provider
          example:
            - name: "client_id"
              value: "your-client-id"
              is_secret: false
            - name: "client_secret"
              value: "your-client-secret"
              is_secret: true
            - name: "scope"
              value: "openid email profile"
              is_secret: false

    IDPResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the identity provider
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Name of the identity provider
          example: "Google"
        description:
          type: string
          description: Description of the identity provider
          example: "Google OIDC identity provider for employee authentication"
        type:
          type: string
          description: Type of the identity provider (e.g., OAUTH)
          example: "GOOGLE"
          enum:
            - OAUTH
            - OIDC
            - GOOGLE
            - GITHUB
        properties:
          type: array
          items:
            $ref: '#/components/schemas/IDPProperty'
          description: Properties of the identity provider
          example:
            - name: "client_id"
              value: "your-client-id"
              is_secret: false
            - name: "client_secret"
              value: "******"
              is_secret: true
            - name: "scope"
              value: "openid email profile"
              is_secret: false

    BasicIDPResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the identity provider
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Name of the identity provider
          example: "Google"
        description:
          type: string
          description: Description of the identity provider
          example: "Google OIDC identity provider for employee authentication"
        type:
          type: string
          description: Type of the identity provider (e.g., OAUTH)
          example: "GOOGLE"
          enum:
            - OAUTH
            - OIDC
            - GOOGLE
            - GITHUB
    
    IDPListResponse:
      type: array
      items:
        $ref: '#/components/schemas/BasicIDPResponse'
      example:
        - id: "550e8400-e29b-41d4-a716-446655440000"
          name: "Google"
          description: "Google OIDC identity provider for employee authentication"
          type: "GOOGLE"
        - id: "660e8400-e29b-41d4-a716-446655440001"
          name: "GitHub"
          description: "GitHub OAuth identity provider for developer authentication"
          type: "GITHUB"

    IDPProperty:
      type: object
      properties:
        name:
          type: string
          description: Name of the property
          example: "your-client-id"
        value:
          type: string
          description: Value of the property
          example: "your-client-id"
        is_secret:
          type: boolean
          description: Whether the property is secret
          example: false

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        description:
          type: string
          description: Detailed error description

    ClientErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          properties:
            code:
              example: "IDP-1001"
            message:
              example: "Identity provider not found"
            description:
              example: "The requested identity provider could not be found"

    ServerErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          properties:
            code:
              example: "IDP-5000"
            message:
              example: "Internal server error"
            description:
              example: "An unexpected error occurred while processing the request"
